import type { ScenarioPreset, ScenarioPresetId, TrainingConfig, TrainingBackend } from '../types';

// ─── Scenario Presets ───────────────────────────────────────────────────────

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'small_objects',
    icon: 'fas fa-crosshairs',
    color: 'border-yellow-500/30 bg-yellow-500/5 hover:bg-yellow-500/10',
    selectedColor: 'border-yellow-500 bg-yellow-500/20',
    suggestedModelSize: 'n',
    suggestedImgsz: 320,
    config: {
      epochs: 250,
      batchSize: -1,
      imgsz: 320,
      optimizer: 'auto',
      lr0: 0.015,
      lrf: 0.001,
      patience: 40,
      cos_lr: true,
      warmup_epochs: 5.0,
      warmup_momentum: 0.8,
      warmup_bias_lr: 0.1,
      momentum: 0.937,
      weight_decay: 0.0005,
      nbs: 64,
      box: 10.0,
      cls: 1.5,
      dfl: 0.0,
      close_mosaic: 25,
      max_det: 20,
      multi_scale: 0.15,
      rect: true,
      cache: 'ram',
      amp: true,
      single_cls: false,
      pretrained: true,
      freeze: 8,
      augmentation: {
        mosaic: 0.5,
        mixup: 0.05,
        hsv_h: 0.01,
        hsv_s: 0.3,
        hsv_v: 0.2,
        flipud: 0.0,
        fliplr: 0.0,
        degrees: 0.0,
        scale: 0.2,
        shear: 0.0,
        perspective: 0.0,
        copy_paste: 0.0,
        erasing: 0.2,
        translate: 0.15,
      },
    },
  },
  {
    id: 'industrial',
    icon: 'fas fa-industry',
    color: 'border-blue-500/30 bg-blue-500/5 hover:bg-blue-500/10',
    selectedColor: 'border-blue-500 bg-blue-500/20',
    suggestedModelSize: 's',
    suggestedImgsz: 640,
    config: {
      epochs: 300,
      batchSize: -1,
      imgsz: 640,
      optimizer: 'auto',
      lr0: 0.01,
      lrf: 0.001,
      patience: 50,
      cos_lr: true,
      warmup_epochs: 3.0,
      warmup_momentum: 0.8,
      warmup_bias_lr: 0.1,
      momentum: 0.937,
      weight_decay: 0.0005,
      nbs: 64,
      box: 10.0,
      cls: 2.0,
      dfl: 0.0,
      close_mosaic: 30,
      max_det: 50,
      multi_scale: 0.0,
      rect: false,
      cache: 'ram',
      amp: true,
      single_cls: false,
      pretrained: true,
      freeze: 10,
      augmentation: {
        mosaic: 0.3,
        mixup: 0.0,
        hsv_h: 0.005,
        hsv_s: 0.15,
        hsv_v: 0.1,
        flipud: 0.0,
        fliplr: 0.0,
        degrees: 0.0,
        scale: 0.1,
        shear: 0.0,
        perspective: 0.0,
        copy_paste: 0.0,
        erasing: 0.1,
        translate: 0.05,
      },
    },
  },
  {
    id: 'traffic',
    icon: 'fas fa-car',
    color: 'border-green-500/30 bg-green-500/5 hover:bg-green-500/10',
    selectedColor: 'border-green-500 bg-green-500/20',
    suggestedModelSize: 's',
    suggestedImgsz: 640,
    config: {
      epochs: 200,
      batchSize: 16,
      imgsz: 640,
      optimizer: 'auto',
      lr0: 0.01,
      lrf: 0.01,
      patience: 60,
      cos_lr: true,
      warmup_epochs: 3.0,
      warmup_momentum: 0.8,
      warmup_bias_lr: 0.1,
      momentum: 0.937,
      weight_decay: 0.0005,
      nbs: 64,
      box: 7.5,
      cls: 0.5,
      dfl: 0.0,
      close_mosaic: 15,
      max_det: 500,
      multi_scale: 0.3,
      rect: false,
      cache: 'ram',
      amp: true,
      single_cls: false,
      pretrained: true,
      freeze: null,
      augmentation: {
        mosaic: 1.0,
        mixup: 0.15,
        hsv_h: 0.015,
        hsv_s: 0.7,
        hsv_v: 0.4,
        flipud: 0.0,
        fliplr: 0.5,
        degrees: 0.0,
        scale: 0.5,
        shear: 0.0,
        perspective: 0.0001,
        copy_paste: 0.0,
        erasing: 0.4,
        translate: 0.2,
      },
    },
  },
  {
    id: 'edge_mobile',
    icon: 'fas fa-mobile-alt',
    color: 'border-orange-500/30 bg-orange-500/5 hover:bg-orange-500/10',
    selectedColor: 'border-orange-500 bg-orange-500/20',
    suggestedModelSize: 'n',
    suggestedImgsz: 256,
    config: {
      epochs: 300,
      batchSize: -1,
      imgsz: 256,
      optimizer: 'auto',
      lr0: 0.02,
      lrf: 0.001,
      patience: 50,
      cos_lr: true,
      warmup_epochs: 5.0,
      warmup_momentum: 0.8,
      warmup_bias_lr: 0.1,
      momentum: 0.937,
      weight_decay: 0.0005,
      nbs: 64,
      box: 8.0,
      cls: 1.0,
      dfl: 0.0,
      close_mosaic: 30,
      max_det: 10,
      multi_scale: 0.2,
      rect: true,
      cache: 'ram',
      amp: true,
      single_cls: false,
      pretrained: true,
      freeze: null,
      augmentation: {
        mosaic: 0.4,
        mixup: 0.0,
        hsv_h: 0.015,
        hsv_s: 0.5,
        hsv_v: 0.3,
        flipud: 0.0,
        fliplr: 0.5,
        degrees: 0.0,
        scale: 0.3,
        shear: 0.0,
        perspective: 0.0,
        copy_paste: 0.0,
        erasing: 0.15,
        translate: 0.1,
      },
    },
  },
  {
    id: 'medical',
    icon: 'fas fa-heartbeat',
    color: 'border-red-500/30 bg-red-500/5 hover:bg-red-500/10',
    selectedColor: 'border-red-500 bg-red-500/20',
    suggestedModelSize: 'm',
    suggestedImgsz: 640,
    config: {
      epochs: 500,
      batchSize: 8,
      imgsz: 640,
      optimizer: 'auto',
      lr0: 0.005,
      lrf: 0.0005,
      patience: 80,
      cos_lr: true,
      warmup_epochs: 5.0,
      warmup_momentum: 0.8,
      warmup_bias_lr: 0.1,
      momentum: 0.937,
      weight_decay: 0.001,
      nbs: 64,
      box: 10.0,
      cls: 2.0,
      dfl: 0.0,
      close_mosaic: 40,
      max_det: 100,
      multi_scale: 0.0,
      rect: false,
      cache: 'ram',
      amp: true,
      single_cls: false,
      pretrained: true,
      freeze: 12,
      augmentation: {
        mosaic: 0.3,
        mixup: 0.1,
        hsv_h: 0.01,
        hsv_s: 0.3,
        hsv_v: 0.3,
        flipud: 0.5,
        fliplr: 0.5,
        degrees: 15.0,
        scale: 0.3,
        shear: 0.0,
        perspective: 0.0,
        copy_paste: 0.0,
        erasing: 0.3,
        translate: 0.15,
      },
    },
  },
  {
    id: 'aerial',
    icon: 'fas fa-satellite',
    color: 'border-purple-500/30 bg-purple-500/5 hover:bg-purple-500/10',
    selectedColor: 'border-purple-500 bg-purple-500/20',
    suggestedModelSize: 'm',
    suggestedImgsz: 960,
    config: {
      epochs: 200,
      batchSize: 8,
      imgsz: 960,
      optimizer: 'auto',
      lr0: 0.01,
      lrf: 0.01,
      patience: 50,
      cos_lr: true,
      warmup_epochs: 3.0,
      warmup_momentum: 0.8,
      warmup_bias_lr: 0.1,
      momentum: 0.937,
      weight_decay: 0.0005,
      nbs: 64,
      box: 12.0,
      cls: 0.5,
      dfl: 0.0,
      close_mosaic: 15,
      max_det: 1000,
      multi_scale: 0.5,
      rect: false,
      cache: 'disk',
      amp: true,
      single_cls: false,
      pretrained: true,
      freeze: null,
      augmentation: {
        mosaic: 1.0,
        mixup: 0.1,
        hsv_h: 0.015,
        hsv_s: 0.7,
        hsv_v: 0.4,
        flipud: 0.5,
        fliplr: 0.5,
        degrees: 180.0,
        scale: 0.5,
        shear: 5.0,
        perspective: 0.0005,
        copy_paste: 0.0,
        erasing: 0.4,
        translate: 0.2,
      },
    },
  },
];

export function getPresetById(id: ScenarioPresetId): ScenarioPreset | undefined {
  return SCENARIO_PRESETS.find((p) => p.id === id);
}

// ─── Optimizers & Export Formats ────────────────────────────────────────────

export const OPTIMIZERS = [
  { value: 'auto', label: 'Auto' },
  { value: 'SGD', label: 'SGD' },
  { value: 'Adam', label: 'Adam' },
  { value: 'AdamW', label: 'AdamW' },
  { value: 'NAdam', label: 'NAdam' },
  { value: 'RAdam', label: 'RAdam' },
  { value: 'RMSProp', label: 'RMSProp' },
];

export const EXPORT_FORMATS = [
  { value: 'onnx', label: 'ONNX' },
  { value: 'torchscript', label: 'TorchScript' },
  { value: 'engine', label: 'TensorRT' },
  { value: 'coreml', label: 'CoreML' },
  { value: 'tflite', label: 'TFLite' },
  { value: 'openvino', label: 'OpenVINO' },
];

// ─── Default Config ─────────────────────────────────────────────────────────

export function getDefaultConfig(): TrainingConfig {
  const base = SCENARIO_PRESETS[0].config; // small_objects
  return {
    yoloVersion: 'yolo11',
    task: 'detect',
    modelSize: 'n',
    device: 'auto',
    valSplit: 0.2,
    workers: 4,
    exportFormats: [],
    resume: false,
    ...base,
    augmentation: { ...base.augmentation },
  };
}

// ─── Default Common Params per Backend ────────────────────────────────────────

export interface BackendDefaults {
  epochs: number;
  batchSize: number;
  imageSize: number;
  lr: number;
  patience: number;
}

export const BACKEND_DEFAULTS: Record<TrainingBackend, BackendDefaults> = {
  yolo: { epochs: 100, batchSize: -1, imageSize: 640, lr: 0.01, patience: 50 },
  rt_detr: { epochs: 72, batchSize: 8, imageSize: 640, lr: 0.0002, patience: 50 },
  rf_detr: { epochs: 50, batchSize: 8, imageSize: 560, lr: 0.0004, patience: 30 },
  mmdetection: { epochs: 12, batchSize: 4, imageSize: 800, lr: 0.02, patience: 0 },
  smp: { epochs: 50, batchSize: 8, imageSize: 512, lr: 0.0001, patience: 10 },
  hf_segmentation: { epochs: 50, batchSize: 4, imageSize: 512, lr: 0.00006, patience: 10 },
  mmsegmentation: { epochs: 40, batchSize: 4, imageSize: 512, lr: 0.0001, patience: 0 },
  detectron2: { epochs: 50, batchSize: 4, imageSize: 800, lr: 0.0025, patience: 0 },
  mmpose: { epochs: 210, batchSize: 32, imageSize: 256, lr: 0.0005, patience: 0 },
  mmrotate: { epochs: 12, batchSize: 4, imageSize: 1024, lr: 0.01, patience: 0 },
  timm: { epochs: 100, batchSize: 32, imageSize: 224, lr: 0.001, patience: 10 },
  hf_classification: { epochs: 30, batchSize: 16, imageSize: 224, lr: 0.00005, patience: 5 },
  tsai: { epochs: 100, batchSize: 64, imageSize: 0, lr: 0.001, patience: 10 },
  pytorch_forecasting: { epochs: 100, batchSize: 64, imageSize: 0, lr: 0.001, patience: 10 },
  pyod: { epochs: 100, batchSize: 64, imageSize: 0, lr: 0.001, patience: 0 },
  tslearn: { epochs: 50, batchSize: 0, imageSize: 0, lr: 0.001, patience: 0 },
  pypots: { epochs: 100, batchSize: 32, imageSize: 0, lr: 0.01, patience: 10 },
  stumpy: { epochs: 1, batchSize: 0, imageSize: 0, lr: 0.001, patience: 0 },
  sklearn: { epochs: 1, batchSize: 0, imageSize: 0, lr: 0.01, patience: 0 },
};
