/* ─── Types ──────────────────────────────────────────────────────────────── */

export interface ModelEntry {
  id: string;
  name: string;
  backend: string;
  backendName: string;
  description: string;
  params: string | null;
  tasks: string[];
  sizes: string[] | null;
  recommended: boolean;
}

export interface BackendMeta {
  id: string;
  name: string;
  icon: string;
  iconColor: string;
  datasetFormat: string;
  pipPackages: string[];
  scriptTemplate: string;
}

/* ─── Backend Metadata ───────────────────────────────────────────────────── */

export const BACKEND_META: BackendMeta[] = [
  { id: 'yolo', name: 'YOLO', icon: 'fas fa-bolt', iconColor: 'text-yellow-500', datasetFormat: 'YOLO TXT', pipPackages: ['ultralytics'],
    scriptTemplate: `#!/usr/bin/env python3
"""YOLO Training Script - Generated by Annotix"""
import sys, json, os

def main():
    from ultralytics import YOLO

    data_yaml = r"/path/to/data.yaml"
    model = YOLO("yolo11n.pt")

    train_args = {
        "data": data_yaml,
        "epochs": 100, "batch": 16, "imgsz": 640,
        "device": "", "optimizer": "auto",
        "lr0": 0.01, "patience": 50, "workers": 8,
        "project": os.path.dirname(data_yaml),
        "name": "train", "exist_ok": True, "amp": True,
        "mosaic": 1.0, "mixup": 0.0, "fliplr": 0.5,
    }

    def on_fit_epoch_end(trainer):
        epoch = trainer.epoch + 1
        total = trainer.epochs
        metrics = {}
        if hasattr(trainer, 'metrics') and isinstance(trainer.metrics, dict):
            m = trainer.metrics
            metrics["mAP50"] = m.get("metrics/mAP50(B)")
            metrics["mAP50_95"] = m.get("metrics/mAP50-95(B)")
        event = {"type": "epoch", "epoch": epoch,
                 "totalEpochs": total,
                 "progress": (epoch / total) * 100.0,
                 "metrics": metrics}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    model.add_callback("on_fit_epoch_end", on_fit_epoch_end)
    results = model.train(**train_args)

    best = os.path.join(os.path.dirname(data_yaml), "train/weights/best.pt")
    result = {"type": "completed",
              "bestModelPath": best if os.path.exists(best) else None}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()` },
  { id: 'rt_detr', name: 'RT-DETR', icon: 'fas fa-atom', iconColor: 'text-cyan-500', datasetFormat: 'YOLO TXT', pipPackages: ['ultralytics'],
    scriptTemplate: `#!/usr/bin/env python3
"""RT-DETR Training Script - Generated by Annotix"""
import sys, json, os

def main():
    from ultralytics import RTDETR

    data_yaml = r"/path/to/data.yaml"
    model = RTDETR("rtdetr-l.pt")

    train_args = {
        "data": data_yaml,
        "epochs": 100, "batch": 16, "imgsz": 640,
        "device": "", "optimizer": "AdamW",
        "lr0": 0.0001, "patience": 50,
        "warmup_epochs": 3.0, "weight_decay": 0.0001,
        "amp": True,
    }

    def on_fit_epoch_end(trainer):
        epoch = trainer.epoch + 1
        total = trainer.epochs
        metrics = {}
        if hasattr(trainer, 'metrics') and isinstance(trainer.metrics, dict):
            metrics["mAP50"] = trainer.metrics.get("metrics/mAP50(B)")
        event = {"type": "epoch", "epoch": epoch,
                 "totalEpochs": total,
                 "progress": (epoch / total) * 100.0,
                 "metrics": metrics}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    model.add_callback("on_fit_epoch_end", on_fit_epoch_end)
    model.train(**train_args)

    best = os.path.join(os.path.dirname(data_yaml), "train/weights/best.pt")
    result = {"type": "completed",
              "bestModelPath": best if os.path.exists(best) else None}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()` },
  { id: 'rf_detr', name: 'RF-DETR', icon: 'fas fa-crosshairs', iconColor: 'text-violet-500', datasetFormat: 'COCO JSON', pipPackages: ['rfdetr'],
    scriptTemplate: `#!/usr/bin/env python3
"""RF-DETR Training Script - Generated by Annotix"""
import sys, json, os

def main():
    from rfdetr import RFDETRBase

    model = RFDETRBase()
    dataset_dir = r"/path/to/dataset"
    output_dir = os.path.join(dataset_dir, "train_output")
    os.makedirs(output_dir, exist_ok=True)

    model.train(
        dataset_dir=dataset_dir,
        epochs=100, batch_size=16, resolution=560,
        lr=1e-4, lr_encoder=1e-5,
        grad_accum_steps=4, use_ema=True,
        weight_decay=0.0001,
    )

    best = None
    for name in ["checkpoint_best_total.pth", "checkpoint_best.pth"]:
        candidate = os.path.join(output_dir, name)
        if os.path.exists(candidate):
            best = candidate
            break

    result = {"type": "completed", "bestModelPath": best}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()` },
  { id: 'mmdetection', name: 'MMDetection', icon: 'fas fa-layer-group', iconColor: 'text-blue-500', datasetFormat: 'COCO JSON', pipPackages: ['openmim', 'mmengine', 'mmcv', 'mmdet'],
    scriptTemplate: `#!/usr/bin/env python3
"""MMDetection Training Script - Generated by Annotix"""
import sys, json, os, glob

def main():
    from mmengine.config import Config
    from mmengine.runner import Runner
    from mmengine.hooks import Hook

    class AnnotixHook(Hook):
        def after_train_epoch(self, runner):
            epoch = runner.epoch + 1
            total = runner.max_epochs
            metrics = {}
            if hasattr(runner, 'message_hub'):
                logs = runner.message_hub.log_scalars
                if "train/loss" in logs:
                    metrics["trainLoss"] = float(logs["train/loss"].current())
            event = {"type": "epoch", "epoch": epoch,
                     "totalEpochs": total,
                     "progress": (epoch/total)*100,
                     "metrics": metrics}
            print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    cfg = Config.fromfile(r"/path/to/mmdet_config.py")
    cfg.work_dir = "./train"
    runner = Runner.from_cfg(cfg)
    runner.register_hook(AnnotixHook(), priority="LOW")
    runner.train()

    best_files = sorted(glob.glob(os.path.join(cfg.work_dir, "best_*.pth")))
    result = {"type": "completed",
              "bestModelPath": best_files[-1] if best_files else None}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()` },
  { id: 'smp', name: 'SMP', icon: 'fas fa-puzzle-piece', iconColor: 'text-emerald-500', datasetFormat: 'PNG Masks', pipPackages: ['segmentation-models-pytorch', 'torch', 'torchvision', 'albumentations'],
    scriptTemplate: `#!/usr/bin/env python3
"""SMP Training Script - Generated by Annotix"""
import sys, json, os, torch

def main():
    import segmentation_models_pytorch as smp

    model = smp.Unet(
        encoder_name="resnet34",
        encoder_weights="imagenet",
        in_channels=3, classes=NUM_CLASSES,
    )
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
    loss_fn = smp.losses.DiceLoss(mode="multiclass")

    for epoch in range(1, EPOCHS + 1):
        model.train()
        train_loss = 0
        for images, masks in train_loader:
            pred = model(images)
            loss = loss_fn(pred, masks)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss += loss.item()

        event = {"type": "epoch", "epoch": epoch,
                 "totalEpochs": EPOCHS,
                 "progress": (epoch/EPOCHS)*100,
                 "metrics": {"trainLoss": train_loss/len(train_loader)}}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    torch.save(model.state_dict(), "best.pth")
    result = {"type": "completed", "bestModelPath": "best.pth"}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()` },
  { id: 'hf_segmentation', name: 'HuggingFace Seg', icon: 'fas fa-face-smile', iconColor: 'text-amber-500', datasetFormat: 'PNG Masks', pipPackages: ['transformers', 'datasets', 'evaluate', 'torch', 'torchvision'],
    scriptTemplate: `#!/usr/bin/env python3
"""HuggingFace Segmentation Script - Generated by Annotix"""
import sys, json, os, torch

def main():
    from transformers import (
        SegformerForSemanticSegmentation,
        SegformerImageProcessor,
        TrainingArguments, Trainer,
    )

    model_name = "nvidia/mit-b0"
    processor = SegformerImageProcessor.from_pretrained(model_name)
    model = SegformerForSemanticSegmentation.from_pretrained(
        model_name, num_labels=NUM_CLASSES,
        ignore_mismatched_sizes=True,
    )

    training_args = TrainingArguments(
        output_dir="./train",
        num_train_epochs=100,
        per_device_train_batch_size=16,
        learning_rate=6e-5, warmup_ratio=0.1,
        weight_decay=0.01,
        evaluation_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
    )

    trainer = Trainer(
        model=model, args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
    )
    trainer.train()

    result = {"type": "completed", "bestModelPath": "./train/best"}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()` },
  { id: 'mmsegmentation', name: 'MMSegmentation', icon: 'fas fa-shapes', iconColor: 'text-rose-500', datasetFormat: 'PNG Masks', pipPackages: ['openmim', 'mmengine', 'mmcv', 'mmsegmentation'],
    scriptTemplate: `#!/usr/bin/env python3
"""MMSegmentation Training Script - Generated by Annotix"""
import sys, json, os, glob

def main():
    from mmengine.config import Config
    from mmengine.runner import Runner
    from mmengine.hooks import Hook

    class AnnotixHook(Hook):
        def after_train_epoch(self, runner):
            epoch = runner.epoch + 1
            total = runner.max_epochs
            metrics = {}
            if hasattr(runner, 'message_hub'):
                logs = runner.message_hub.log_scalars
                if "train/loss" in logs:
                    metrics["trainLoss"] = float(logs["train/loss"].current())
                if "val/mIoU" in logs:
                    metrics["meanIoU"] = float(logs["val/mIoU"].current())
            event = {"type": "epoch", "epoch": epoch,
                     "totalEpochs": total,
                     "progress": (epoch/total)*100,
                     "metrics": metrics}
            print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    cfg = Config.fromfile(r"/path/to/mmseg_config.py")
    cfg.work_dir = "./train"
    runner = Runner.from_cfg(cfg)
    runner.register_hook(AnnotixHook(), priority="LOW")
    runner.train()

    best_files = sorted(glob.glob(os.path.join(cfg.work_dir, "best_*.pth")))
    result = {"type": "completed",
              "bestModelPath": best_files[-1] if best_files else None}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()` },
  { id: 'detectron2', name: 'Detectron2', icon: 'fas fa-mask', iconColor: 'text-indigo-500', datasetFormat: 'COCO Instance JSON', pipPackages: ['detectron2'],
    scriptTemplate: '#!/usr/bin/env python3\n"""Detectron2 Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'mmpose', name: 'MMPose', icon: 'fas fa-person', iconColor: 'text-lime-500', datasetFormat: 'COCO Keypoints JSON', pipPackages: ['openmim', 'mmengine', 'mmcv', 'mmpose', 'mmdet'],
    scriptTemplate: '#!/usr/bin/env python3\n"""MMPose Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'mmrotate', name: 'MMRotate', icon: 'fas fa-rotate', iconColor: 'text-fuchsia-500', datasetFormat: 'DOTA TXT', pipPackages: ['openmim', 'mmengine', 'mmcv', 'mmrotate'],
    scriptTemplate: '#!/usr/bin/env python3\n"""MMRotate Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'timm', name: 'timm', icon: 'fas fa-image', iconColor: 'text-sky-500', datasetFormat: 'ImageFolder', pipPackages: ['timm', 'torch', 'torchvision'],
    scriptTemplate: '#!/usr/bin/env python3\n"""timm Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'hf_classification', name: 'HuggingFace Cls', icon: 'fas fa-face-smile', iconColor: 'text-orange-500', datasetFormat: 'ImageFolder', pipPackages: ['transformers', 'datasets', 'evaluate', 'torch', 'torchvision'],
    scriptTemplate: '#!/usr/bin/env python3\n"""HuggingFace Classification - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'tsai', name: 'tsai', icon: 'fas fa-chart-line', iconColor: 'text-teal-500', datasetFormat: 'TimeSeries CSV', pipPackages: ['tsai'],
    scriptTemplate: '#!/usr/bin/env python3\n"""tsai Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'pytorch_forecasting', name: 'PyTorch Forecasting', icon: 'fas fa-chart-area', iconColor: 'text-blue-400', datasetFormat: 'TimeSeries CSV', pipPackages: ['pytorch-forecasting', 'pytorch-lightning', 'torch'],
    scriptTemplate: '#!/usr/bin/env python3\n"""PyTorch Forecasting - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'pyod', name: 'PyOD', icon: 'fas fa-triangle-exclamation', iconColor: 'text-red-500', datasetFormat: 'TimeSeries CSV', pipPackages: ['pyod', 'torch'],
    scriptTemplate: '#!/usr/bin/env python3\n"""PyOD Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'tslearn', name: 'tslearn', icon: 'fas fa-circle-nodes', iconColor: 'text-purple-500', datasetFormat: 'TimeSeries CSV', pipPackages: ['tslearn', 'scikit-learn'],
    scriptTemplate: '#!/usr/bin/env python3\n"""tslearn Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'pypots', name: 'PyPOTS', icon: 'fas fa-fill-drip', iconColor: 'text-cyan-400', datasetFormat: 'TimeSeries CSV', pipPackages: ['pypots', 'torch'],
    scriptTemplate: '#!/usr/bin/env python3\n"""PyPOTS Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'stumpy', name: 'STUMPY', icon: 'fas fa-magnifying-glass-chart', iconColor: 'text-amber-600', datasetFormat: 'TimeSeries CSV', pipPackages: ['stumpy', 'numpy'],
    scriptTemplate: '#!/usr/bin/env python3\n"""STUMPY Training - Generated by Annotix"""\n# See Rust backend for full script' },
  { id: 'sklearn', name: 'Scikit-learn', icon: 'fas fa-table', iconColor: 'text-emerald-600', datasetFormat: 'Tabular CSV', pipPackages: ['scikit-learn', 'xgboost', 'lightgbm', 'pandas', 'skl2onnx', 'onnxmltools'],
    scriptTemplate: '#!/usr/bin/env python3\n"""Sklearn Training - Generated by Annotix"""\n# See Rust backend for full script' },
];

/* ─── All Models ─────────────────────────────────────────────────────────── */

export const ALL_MODELS: ModelEntry[] = [
  // YOLO
  { id: 'yolo26', name: 'YOLO26', backend: 'yolo', backendName: 'YOLO', description: 'Latest architecture with improved accuracy', params: null, tasks: ['detect','segment','classify','pose','obb'], sizes: ['n','s','m','l','x'], recommended: true },
  { id: 'yolo12', name: 'YOLO12', backend: 'yolo', backendName: 'YOLO', description: 'Attention-based architecture', params: null, tasks: ['detect','segment','classify'], sizes: ['n','s','m','l','x'], recommended: false },
  { id: 'yolo11', name: 'YOLO11', backend: 'yolo', backendName: 'YOLO', description: 'Robust and battle-tested', params: null, tasks: ['detect','segment','classify','pose','obb'], sizes: ['n','s','m','l','x'], recommended: false },
  { id: 'yolov10', name: 'YOLOv10', backend: 'yolo', backendName: 'YOLO', description: 'NMS-free real-time detection', params: null, tasks: ['detect'], sizes: ['n','s','m','l','x'], recommended: false },
  { id: 'yolov9', name: 'YOLOv9', backend: 'yolo', backendName: 'YOLO', description: 'Programmable gradient information', params: null, tasks: ['detect','segment'], sizes: ['t','s','m','c','e'], recommended: false },
  { id: 'yolov8', name: 'YOLOv8', backend: 'yolo', backendName: 'YOLO', description: 'Widely adopted version', params: null, tasks: ['detect','segment','classify','pose','obb'], sizes: ['n','s','m','l','x'], recommended: false },
  { id: 'yolov5', name: 'YOLOv5u', backend: 'yolo', backendName: 'YOLO', description: 'Classic with anchor-free head', params: null, tasks: ['detect','segment','classify'], sizes: ['n','s','m','l','x'], recommended: false },
  // RT-DETR
  { id: 'rtdetr-l', name: 'RT-DETR-L', backend: 'rt_detr', backendName: 'RT-DETR', description: 'ResNet-50 backbone', params: '32M', tasks: ['detect'], sizes: null, recommended: true },
  { id: 'rtdetr-x', name: 'RT-DETR-X', backend: 'rt_detr', backendName: 'RT-DETR', description: 'ResNet-101 backbone', params: '67M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'rtdetrv2-s', name: 'RT-DETRv2-S', backend: 'rt_detr', backendName: 'RT-DETR', description: 'Improved decoder — small', params: '20M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'rtdetrv2-m', name: 'RT-DETRv2-M', backend: 'rt_detr', backendName: 'RT-DETR', description: 'Improved decoder — medium', params: '36M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'rtdetrv2-l', name: 'RT-DETRv2-L', backend: 'rt_detr', backendName: 'RT-DETR', description: 'Improved decoder — large', params: '42M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'rtdetrv2-x', name: 'RT-DETRv2-X', backend: 'rt_detr', backendName: 'RT-DETR', description: 'Improved decoder — extra large', params: '76M', tasks: ['detect'], sizes: null, recommended: false },
  // RF-DETR
  { id: 'RFDETRNano', name: 'RF-DETR Nano', backend: 'rf_detr', backendName: 'RF-DETR', description: 'Ultra-lightweight for edge', params: '2.4M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'RFDETRSmall', name: 'RF-DETR Small', backend: 'rf_detr', backendName: 'RF-DETR', description: 'Compact with strong accuracy', params: '8.3M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'RFDETRMedium', name: 'RF-DETR Medium', backend: 'rf_detr', backendName: 'RF-DETR', description: 'Balanced speed/accuracy', params: '22M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'RFDETRBase', name: 'RF-DETR Base', backend: 'rf_detr', backendName: 'RF-DETR', description: 'Best accuracy/speed trade-off', params: '29M', tasks: ['detect'], sizes: null, recommended: true },
  { id: 'RFDETRLarge', name: 'RF-DETR Large', backend: 'rf_detr', backendName: 'RF-DETR', description: 'Maximum accuracy', params: '128M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'RFDETRBaseSeg', name: 'RF-DETR Base Seg', backend: 'rf_detr', backendName: 'RF-DETR', description: 'Instance segmentation (preview)', params: '31M', tasks: ['segment'], sizes: null, recommended: false },
  // MMDetection
  { id: 'faster-rcnn', name: 'Faster R-CNN', backend: 'mmdetection', backendName: 'MMDetection', description: 'Classic two-stage with ResNet-50 + FPN', params: '41M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'cascade-rcnn', name: 'Cascade R-CNN', backend: 'mmdetection', backendName: 'MMDetection', description: 'Multi-stage cascaded refinement', params: '69M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'retinanet', name: 'RetinaNet', backend: 'mmdetection', backendName: 'MMDetection', description: 'One-stage with focal loss', params: '37M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'fcos', name: 'FCOS', backend: 'mmdetection', backendName: 'MMDetection', description: 'Anchor-free fully convolutional', params: '32M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'rtmdet', name: 'RTMDet-L', backend: 'mmdetection', backendName: 'MMDetection', description: 'Real-time modern detector', params: '52M', tasks: ['detect'], sizes: null, recommended: true },
  { id: 'detr', name: 'DETR', backend: 'mmdetection', backendName: 'MMDetection', description: 'End-to-end detection transformer', params: '41M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'deformable-detr', name: 'Deformable DETR', backend: 'mmdetection', backendName: 'MMDetection', description: 'Deformable attention — faster convergence', params: '40M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'dino', name: 'DINO', backend: 'mmdetection', backendName: 'MMDetection', description: 'SOTA with improved denoising', params: '47M', tasks: ['detect'], sizes: null, recommended: false },
  { id: 'co-detr', name: 'Co-DETR', backend: 'mmdetection', backendName: 'MMDetection', description: 'Collaborative DETR with auxiliary heads', params: '56M', tasks: ['detect'], sizes: null, recommended: false },
  // SMP
  { id: 'smp-unet', name: 'U-Net (ResNet-34)', backend: 'smp', backendName: 'SMP', description: 'Classic encoder-decoder with skip connections', params: '24M', tasks: ['segment'], sizes: null, recommended: true },
  { id: 'smp-unetpp', name: 'U-Net++ (ResNet-50)', backend: 'smp', backendName: 'SMP', description: 'Nested U-Net with dense skip connections', params: '32M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-manet', name: 'MA-Net (ResNet-34)', backend: 'smp', backendName: 'SMP', description: 'Multi-scale Attention Net', params: '22M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-linknet', name: 'LinkNet (ResNet-34)', backend: 'smp', backendName: 'SMP', description: 'Lightweight with residual connections', params: '11M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-fpn', name: 'FPN (ResNet-34)', backend: 'smp', backendName: 'SMP', description: 'Feature Pyramid Network', params: '22M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-pspnet', name: 'PSPNet (ResNet-50)', backend: 'smp', backendName: 'SMP', description: 'Pyramid Scene Parsing', params: '47M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-pan', name: 'PAN (ResNet-34)', backend: 'smp', backendName: 'SMP', description: 'Pyramid Attention Network', params: '24M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-dlv3', name: 'DeepLabV3 (ResNet-50)', backend: 'smp', backendName: 'SMP', description: 'Atrous convolutions + ASPP', params: '40M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-dlv3p', name: 'DeepLabV3+ (ResNet-50)', backend: 'smp', backendName: 'SMP', description: 'DeepLabV3 with improved decoder', params: '40M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-segformer', name: 'SegFormer (MiT-B2)', backend: 'smp', backendName: 'SMP', description: 'Transformer encoder + MLP decoder', params: '25M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-dpt', name: 'DPT (ResNet-50)', backend: 'smp', backendName: 'SMP', description: 'Dense Prediction Transformer', params: '40M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'smp-upernet', name: 'UPerNet (ResNet-50)', backend: 'smp', backendName: 'SMP', description: 'Unified Perceptual Parsing', params: '66M', tasks: ['segment'], sizes: null, recommended: false },
  // HuggingFace
  { id: 'hf-b0', name: 'SegFormer-B0', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Lightweight, ideal for edge', params: '3.7M', tasks: ['segment'], sizes: null, recommended: true },
  { id: 'hf-b1', name: 'SegFormer-B1', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Good speed/accuracy balance', params: '14M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-b2', name: 'SegFormer-B2', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Mid-size recommended balance', params: '25M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-b3', name: 'SegFormer-B3', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'High accuracy variant', params: '47M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-b4', name: 'SegFormer-B4', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Very high accuracy', params: '64M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-b5', name: 'SegFormer-B5', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Maximum accuracy', params: '82M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-mask2f', name: 'Mask2Former (Swin-L)', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'SOTA universal segmentation', params: '200M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-maskf', name: 'MaskFormer (Swin-B)', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Per-pixel via mask prediction', params: '102M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-dpt', name: 'DPT (ViT-Large)', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Dense Prediction Transformer', params: '343M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-beit', name: 'BEiT (Large)', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'BERT-style pretrained ViT', params: '305M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-upernet', name: 'UPerNet (Swin-L)', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Unified Perceptual Parsing', params: '234M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'hf-mobilevit', name: 'MobileViT DeepLabV3', backend: 'hf_segmentation', backendName: 'HuggingFace', description: 'Mobile-optimized for edge', params: '6.4M', tasks: ['segment'], sizes: null, recommended: false },
  // MMSegmentation
  { id: 'mm-fcn', name: 'FCN (R50)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Fully Convolutional Network', params: '49M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-pspnet', name: 'PSPNet (R50)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Pyramid Scene Parsing', params: '49M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-dlv3', name: 'DeepLabV3 (R50)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Atrous spatial pyramid — no decoder', params: '58M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-dlv3p', name: 'DeepLabV3+ (R50)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'ASPP with decoder', params: '44M', tasks: ['segment'], sizes: null, recommended: true },
  { id: 'mm-unet', name: 'UNet (S5-D16)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Encoder-decoder with skip connections', params: '29M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-upernet', name: 'UPerNet (R50)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Unified Perceptual Parsing', params: '66M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-ocrnet', name: 'OCRNet (HR48)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Object-Contextual Representations', params: '70M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-pointrend', name: 'PointRend (R50)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Point-based refinement', params: '38M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-bisev1', name: 'BiSeNetV1', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Two-branch real-time', params: '13M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-bisev2', name: 'BiSeNetV2', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Bilateral segmentation v2', params: '3.4M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-stdc1', name: 'STDC1', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Short-Term Dense Concatenate', params: '8M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-stdc2', name: 'STDC2', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'STDC larger variant', params: '12M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-fastscnn', name: 'Fast-SCNN', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Ultra lightweight', params: '1.1M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-cgnet', name: 'CGNet', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Context Guided Network', params: '0.5M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-erfnet', name: 'ERFNet', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Efficient Residual Factorized', params: '2.1M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-pidnet-s', name: 'PIDNet-S', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'PID-inspired — good balance', params: '7.6M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-pidnet-m', name: 'PIDNet-M', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'PIDNet medium', params: '28M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-pidnet-l', name: 'PIDNet-L', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'PIDNet large — best accuracy', params: '37M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-icnet', name: 'ICNet', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Image Cascade Network', params: '7M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-ddrnet', name: 'DDRNet', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Dual-resolution — fast', params: '20M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-segf-b0', name: 'SegFormer (MiT-B0)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Lightweight transformer', params: '3.8M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-segf-b2', name: 'SegFormer (MiT-B2)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Balanced speed/accuracy', params: '25M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-segf-b5', name: 'SegFormer (MiT-B5)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Highest accuracy', params: '84M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-segmenter', name: 'Segmenter (ViT-B)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Pure ViT segmenter', params: '86M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-setr', name: 'SETR (ViT-L)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Segmentation as sequence', params: '308M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-dpt', name: 'DPT (ViT-B16)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Dense Prediction Transformer', params: '86M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-mask2f', name: 'Mask2Former (Swin-L)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'SOTA universal segmentation', params: '216M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-maskf', name: 'MaskFormer (Swin-B)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Per-pixel via mask prediction', params: '102M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-knet', name: 'K-Net (Swin-L)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Dynamic kernel segmentation', params: '200M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-san', name: 'SAN (ViT-L)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Side Adapter Network (CLIP)', params: '300M', tasks: ['segment'], sizes: null, recommended: false },
  { id: 'mm-segnext', name: 'SegNeXt (Large)', backend: 'mmsegmentation', backendName: 'MMSeg', description: 'Efficient convolutional attention', params: '49M', tasks: ['segment'], sizes: null, recommended: false },
  // Detectron2
  { id: 'dt2-maskrcnn-r50', name: 'Mask R-CNN R50', backend: 'detectron2', backendName: 'Detectron2', description: 'Standard instance segmentation', params: '44M', tasks: ['instance_segment'], sizes: null, recommended: true },
  { id: 'dt2-maskrcnn-r101', name: 'Mask R-CNN R101', backend: 'detectron2', backendName: 'Detectron2', description: 'Deeper backbone', params: '63M', tasks: ['instance_segment'], sizes: null, recommended: false },
  { id: 'dt2-cascade', name: 'Cascade Mask R-CNN', backend: 'detectron2', backendName: 'Detectron2', description: 'Multi-stage cascaded', params: '77M', tasks: ['instance_segment'], sizes: null, recommended: false },
  { id: 'dt2-mask2f', name: 'Mask2Former Swin-L', backend: 'detectron2', backendName: 'Detectron2', description: 'SOTA universal instance seg', params: '216M', tasks: ['instance_segment'], sizes: null, recommended: false },
  { id: 'dt2-pointrend', name: 'PointRend R50', backend: 'detectron2', backendName: 'Detectron2', description: 'Sharp mask boundaries', params: '45M', tasks: ['instance_segment'], sizes: null, recommended: false },
  // MMPose
  { id: 'mmpose-rtmpose-t', name: 'RTMPose-T', backend: 'mmpose', backendName: 'MMPose', description: 'Tiny — fastest', params: '3.3M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-rtmpose-s', name: 'RTMPose-S', backend: 'mmpose', backendName: 'MMPose', description: 'Small — good balance', params: '5.5M', tasks: ['pose','landmarks'], sizes: null, recommended: true },
  { id: 'mmpose-rtmpose-m', name: 'RTMPose-M', backend: 'mmpose', backendName: 'MMPose', description: 'Medium — higher accuracy', params: '13M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-rtmpose-l', name: 'RTMPose-L', backend: 'mmpose', backendName: 'MMPose', description: 'Large — best RTMPose', params: '28M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-hrnet-w32', name: 'HRNet-W32', backend: 'mmpose', backendName: 'MMPose', description: 'High-Resolution Network', params: '29M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-hrnet-w48', name: 'HRNet-W48', backend: 'mmpose', backendName: 'MMPose', description: 'HRNet wider variant', params: '64M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-vitpose-b', name: 'ViTPose-B', backend: 'mmpose', backendName: 'MMPose', description: 'ViT for pose — base', params: '86M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-vitpose-l', name: 'ViTPose-L', backend: 'mmpose', backendName: 'MMPose', description: 'ViTPose — maximum accuracy', params: '307M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-simplebl', name: 'SimpleBaseline R50', backend: 'mmpose', backendName: 'MMPose', description: 'Simple deconv baseline', params: '34M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  { id: 'mmpose-litehrnet', name: 'LiteHRNet-30', backend: 'mmpose', backendName: 'MMPose', description: 'Lightweight, mobile-friendly', params: '1.8M', tasks: ['pose','landmarks'], sizes: null, recommended: false },
  // MMRotate
  { id: 'mmrot-orcnn', name: 'Oriented R-CNN', backend: 'mmrotate', backendName: 'MMRotate', description: 'Two-stage oriented detector', params: '41M', tasks: ['obb'], sizes: null, recommended: true },
  { id: 'mmrot-rfrcnn', name: 'Rotated Faster R-CNN', backend: 'mmrotate', backendName: 'MMRotate', description: 'Faster R-CNN for rotated boxes', params: '41M', tasks: ['obb'], sizes: null, recommended: false },
  { id: 'mmrot-rretinanet', name: 'Rotated RetinaNet', backend: 'mmrotate', backendName: 'MMRotate', description: 'One-stage rotated with focal loss', params: '37M', tasks: ['obb'], sizes: null, recommended: false },
  { id: 'mmrot-roitrans', name: 'RoI Transformer', backend: 'mmrotate', backendName: 'MMRotate', description: 'Spatial transformation for OBB', params: '55M', tasks: ['obb'], sizes: null, recommended: false },
  { id: 'mmrot-glidingv', name: 'Gliding Vertex', backend: 'mmrotate', backendName: 'MMRotate', description: 'Gliding vertex on horizontal bboxes', params: '41M', tasks: ['obb'], sizes: null, recommended: false },
  // timm
  { id: 'timm-mobilenetv3', name: 'MobileNetV3-Large', backend: 'timm', backendName: 'timm', description: 'Mobile-optimized, fast', params: '5.5M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'timm-effnet-b0', name: 'EfficientNet-B0', backend: 'timm', backendName: 'timm', description: 'Efficient scaling — lightweight', params: '5.3M', tasks: ['classify','multi_classify'], sizes: null, recommended: true },
  { id: 'timm-effnet-b3', name: 'EfficientNet-B3', backend: 'timm', backendName: 'timm', description: 'Efficient scaling — balanced', params: '12M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'timm-resnet50', name: 'ResNet-50', backend: 'timm', backendName: 'timm', description: 'Classic residual network', params: '25M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'timm-convnext-t', name: 'ConvNeXt-Tiny', backend: 'timm', backendName: 'timm', description: 'Modern CNN competitive with ViT', params: '28M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'timm-vit-b', name: 'ViT-Base', backend: 'timm', backendName: 'timm', description: 'Vision Transformer base', params: '86M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'timm-swin-b', name: 'Swin-Base', backend: 'timm', backendName: 'timm', description: 'Shifted Window Transformer', params: '88M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'timm-eva02-l', name: 'EVA-02-Large', backend: 'timm', backendName: 'timm', description: 'SOTA vision foundation model', params: '305M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  // HuggingFace Classification
  { id: 'hfcls-vit-b', name: 'ViT-Base', backend: 'hf_classification', backendName: 'HF Cls', description: 'Strong ImageNet baseline', params: '86M', tasks: ['classify','multi_classify'], sizes: null, recommended: true },
  { id: 'hfcls-vit-l', name: 'ViT-Large', backend: 'hf_classification', backendName: 'HF Cls', description: 'Higher accuracy', params: '307M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'hfcls-convnext', name: 'ConvNeXt-Base', backend: 'hf_classification', backendName: 'HF Cls', description: 'Modern CNN competitive with transformers', params: '89M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'hfcls-swin', name: 'Swin-Base', backend: 'hf_classification', backendName: 'HF Cls', description: 'Shifted Window Transformer', params: '88M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'hfcls-deit', name: 'DeiT-Base', backend: 'hf_classification', backendName: 'HF Cls', description: 'Data-efficient with distillation', params: '87M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  { id: 'hfcls-beit', name: 'BEiT-Base', backend: 'hf_classification', backendName: 'HF Cls', description: 'BERT pre-trained Image Transformer', params: '86M', tasks: ['classify','multi_classify'], sizes: null, recommended: false },
  // tsai
  { id: 'tsai-inception', name: 'InceptionTime+', backend: 'tsai', backendName: 'tsai', description: 'Robust for TS classification', params: '0.5M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: true },
  { id: 'tsai-patchtst', name: 'PatchTST', backend: 'tsai', backendName: 'tsai', description: 'Patch-based Transformer', params: '2M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-tst', name: 'TST+', backend: 'tsai', backendName: 'tsai', description: 'Time Series Transformer', params: '1.5M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-tsit', name: 'TSiT+', backend: 'tsai', backendName: 'tsai', description: 'Image-like encoding', params: '3M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-rocket', name: 'ROCKET', backend: 'tsai', backendName: 'tsai', description: 'Random kernels — very fast', params: null, tasks: ['ts_classify'], sizes: null, recommended: false },
  { id: 'tsai-minirocket', name: 'MiniRocket', backend: 'tsai', backendName: 'tsai', description: 'Deterministic ROCKET', params: null, tasks: ['ts_classify'], sizes: null, recommended: false },
  { id: 'tsai-xception', name: 'XceptionTime+', backend: 'tsai', backendName: 'tsai', description: 'Depthwise separable convolutions', params: '0.4M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-resnet', name: 'ResNet+', backend: 'tsai', backendName: 'tsai', description: 'ResNet for time series', params: '0.5M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-lstm', name: 'LSTM+', backend: 'tsai', backendName: 'tsai', description: 'LSTM-based sequential', params: '0.3M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-gru', name: 'GRU+', backend: 'tsai', backendName: 'tsai', description: 'GRU-based lighter', params: '0.2M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-tcn', name: 'TCN', backend: 'tsai', backendName: 'tsai', description: 'Temporal Convolutional Network', params: '0.3M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  { id: 'tsai-omniscale', name: 'OmniScaleCNN', backend: 'tsai', backendName: 'tsai', description: 'Multi-scale CNN', params: '0.4M', tasks: ['ts_classify','ts_forecast','ts_regress','ts_anomaly','ts_segment','ts_event'], sizes: null, recommended: false },
  // PyTorch Forecasting
  { id: 'ptf-tft', name: 'TFT', backend: 'pytorch_forecasting', backendName: 'PyTorch Fcst', description: 'Temporal Fusion Transformer', params: '5M', tasks: ['ts_forecast'], sizes: null, recommended: true },
  { id: 'ptf-nbeats', name: 'N-BEATS', backend: 'pytorch_forecasting', backendName: 'PyTorch Fcst', description: 'Pure DL forecasting', params: '4M', tasks: ['ts_forecast'], sizes: null, recommended: false },
  { id: 'ptf-nhits', name: 'N-HiTS', backend: 'pytorch_forecasting', backendName: 'PyTorch Fcst', description: 'Multi-rate sampling', params: '3M', tasks: ['ts_forecast'], sizes: null, recommended: false },
  { id: 'ptf-deepar', name: 'DeepAR', backend: 'pytorch_forecasting', backendName: 'PyTorch Fcst', description: 'Probabilistic autoregressive', params: '2M', tasks: ['ts_forecast'], sizes: null, recommended: false },
  // PyOD
  { id: 'pyod-ae', name: 'AutoEncoder', backend: 'pyod', backendName: 'PyOD', description: 'Neural network anomaly detection', params: null, tasks: ['ts_anomaly'], sizes: null, recommended: true },
  { id: 'pyod-vae', name: 'VAE', backend: 'pyod', backendName: 'PyOD', description: 'Variational AutoEncoder', params: null, tasks: ['ts_anomaly'], sizes: null, recommended: false },
  { id: 'pyod-ecod', name: 'ECOD', backend: 'pyod', backendName: 'PyOD', description: 'Empirical CDF — unsupervised, fast', params: null, tasks: ['ts_anomaly'], sizes: null, recommended: false },
  { id: 'pyod-iforest', name: 'Isolation Forest', backend: 'pyod', backendName: 'PyOD', description: 'Tree-based isolation', params: null, tasks: ['ts_anomaly'], sizes: null, recommended: false },
  { id: 'pyod-lof', name: 'LOF', backend: 'pyod', backendName: 'PyOD', description: 'Local Outlier Factor', params: null, tasks: ['ts_anomaly'], sizes: null, recommended: false },
  // tslearn
  { id: 'tsl-kmeans-dtw', name: 'K-Means DTW', backend: 'tslearn', backendName: 'tslearn', description: 'Dynamic Time Warping distance', params: null, tasks: ['ts_cluster'], sizes: null, recommended: true },
  { id: 'tsl-kmeans-euc', name: 'K-Means Euclidean', backend: 'tslearn', backendName: 'tslearn', description: 'Standard Euclidean distance', params: null, tasks: ['ts_cluster'], sizes: null, recommended: false },
  { id: 'tsl-kmeans-sdtw', name: 'K-Means Soft-DTW', backend: 'tslearn', backendName: 'tslearn', description: 'Differentiable Soft-DTW', params: null, tasks: ['ts_cluster'], sizes: null, recommended: false },
  { id: 'tsl-kshape', name: 'K-Shape', backend: 'tslearn', backendName: 'tslearn', description: 'Shape-based clustering', params: null, tasks: ['ts_cluster'], sizes: null, recommended: false },
  // PyPOTS
  { id: 'pypots-saits', name: 'SAITS', backend: 'pypots', backendName: 'PyPOTS', description: 'Self-Attention-based Imputation', params: '1M', tasks: ['ts_impute'], sizes: null, recommended: true },
  { id: 'pypots-brits', name: 'BRITS', backend: 'pypots', backendName: 'PyPOTS', description: 'Bidirectional Recurrent Imputation', params: '0.5M', tasks: ['ts_impute'], sizes: null, recommended: false },
  { id: 'pypots-usgan', name: 'US-GAN', backend: 'pypots', backendName: 'PyPOTS', description: 'GAN-based imputation', params: '1.5M', tasks: ['ts_impute'], sizes: null, recommended: false },
  // STUMPY
  { id: 'stumpy-mp', name: 'Matrix Profile', backend: 'stumpy', backendName: 'STUMPY', description: 'Motif/discord discovery', params: null, tasks: ['ts_pattern'], sizes: null, recommended: true },
  { id: 'stumpy-mpdist', name: 'MPdist', backend: 'stumpy', backendName: 'STUMPY', description: 'Similarity search', params: null, tasks: ['ts_pattern'], sizes: null, recommended: false },
  // Sklearn (Tabular ML)
  { id: 'random_forest_classifier', name: 'Random Forest Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Robust ensemble — great default', params: null, tasks: ['tabular'], sizes: null, recommended: true },
  { id: 'xgboost_classifier', name: 'XGBoost Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'State of the art for tabular data', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'lightgbm_classifier', name: 'LightGBM Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Fast on large datasets', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'logistic_regression', name: 'Logistic Regression', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Fast, interpretable baseline', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'svm_classifier', name: 'SVM Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Good for small/medium datasets', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'knn_classifier', name: 'KNN Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Instance-based, no training', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'gradient_boosting_classifier', name: 'Gradient Boosting Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Sklearn native gradient boosting', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'extra_trees_classifier', name: 'Extra Trees Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Faster than Random Forest', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'mlp_classifier', name: 'MLP Classifier', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Neural network classifier', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'random_forest_regressor', name: 'Random Forest Regressor', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Robust ensemble for regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'xgboost_regressor', name: 'XGBoost Regressor', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Gradient boosting regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'lightgbm_regressor', name: 'LightGBM Regressor', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Fast boosting regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'linear_regression', name: 'Linear Regression', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Simple linear baseline', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'ridge_regression', name: 'Ridge Regression', backend: 'sklearn', backendName: 'Scikit-learn', description: 'L2-regularized linear regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'lasso_regression', name: 'Lasso Regression', backend: 'sklearn', backendName: 'Scikit-learn', description: 'L1-regularized — feature selection', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'svr', name: 'SVR', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Support Vector Regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'knn_regressor', name: 'KNN Regressor', backend: 'sklearn', backendName: 'Scikit-learn', description: 'KNN for regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'gradient_boosting_regressor', name: 'Gradient Boosting Regressor', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Sklearn native boosting regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'extra_trees_regressor', name: 'Extra Trees Regressor', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Fast randomized trees regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
  { id: 'mlp_regressor', name: 'MLP Regressor', backend: 'sklearn', backendName: 'Scikit-learn', description: 'Neural network regression', params: null, tasks: ['tabular'], sizes: null, recommended: false },
];

/* ─── Constants ──────────────────────────────────────────────────────────── */

export const ALL_TASKS = [
  'detect', 'segment', 'instance_segment', 'classify', 'multi_classify', 'pose', 'landmarks', 'obb',
  'ts_classify', 'ts_forecast', 'ts_anomaly', 'ts_segment', 'ts_pattern', 'ts_event', 'ts_regress', 'ts_cluster', 'ts_impute',
  'tabular',
] as const;

export const TASK_LABELS: Record<string, string> = {
  detect: 'Detection', segment: 'Segmentation', instance_segment: 'Instance Seg',
  classify: 'Classification', multi_classify: 'Multi-Label', pose: 'Pose', landmarks: 'Landmarks', obb: 'OBB',
  ts_classify: 'TS Classification', ts_forecast: 'Forecasting', ts_anomaly: 'Anomaly Detection',
  ts_segment: 'TS Segmentation', ts_pattern: 'Pattern Recognition', ts_event: 'Event Detection',
  ts_regress: 'TS Regression', ts_cluster: 'Clustering', ts_impute: 'Imputation',
  tabular: 'Tabular ML',
};

export const SIZE_LABELS: Record<string, string> = {
  n: 'Nano', s: 'Small', m: 'Medium', l: 'Large', x: 'XL', t: 'Tiny', c: 'Compact', e: 'Extended',
};

export const BACKEND_COLORS: Record<string, string> = {
  yolo: 'bg-yellow-100 text-yellow-700',
  rt_detr: 'bg-cyan-100 text-cyan-700',
  rf_detr: 'bg-violet-100 text-violet-700',
  mmdetection: 'bg-blue-100 text-blue-700',
  smp: 'bg-emerald-100 text-emerald-700',
  hf_segmentation: 'bg-amber-100 text-amber-700',
  mmsegmentation: 'bg-rose-100 text-rose-700',
  detectron2: 'bg-indigo-100 text-indigo-700',
  mmpose: 'bg-lime-100 text-lime-700',
  mmrotate: 'bg-fuchsia-100 text-fuchsia-700',
  timm: 'bg-sky-100 text-sky-700',
  hf_classification: 'bg-orange-100 text-orange-700',
  tsai: 'bg-teal-100 text-teal-700',
  pytorch_forecasting: 'bg-blue-100 text-blue-600',
  pyod: 'bg-red-100 text-red-700',
  tslearn: 'bg-purple-100 text-purple-700',
  pypots: 'bg-cyan-100 text-cyan-600',
  stumpy: 'bg-amber-100 text-amber-600',
  sklearn: 'bg-emerald-100 text-emerald-700',
};

export const TASK_COLORS: Record<string, string> = {
  detect: 'bg-blue-100 text-blue-700',
  segment: 'bg-purple-100 text-purple-700',
  instance_segment: 'bg-indigo-100 text-indigo-700',
  classify: 'bg-teal-100 text-teal-700',
  multi_classify: 'bg-emerald-100 text-emerald-700',
  pose: 'bg-orange-100 text-orange-700',
  landmarks: 'bg-lime-100 text-lime-700',
  obb: 'bg-pink-100 text-pink-700',
  ts_classify: 'bg-cyan-100 text-cyan-700',
  ts_forecast: 'bg-sky-100 text-sky-700',
  ts_anomaly: 'bg-red-100 text-red-700',
  ts_segment: 'bg-violet-100 text-violet-700',
  ts_pattern: 'bg-amber-100 text-amber-700',
  ts_event: 'bg-fuchsia-100 text-fuchsia-700',
  ts_regress: 'bg-rose-100 text-rose-700',
  ts_cluster: 'bg-purple-100 text-purple-600',
  ts_impute: 'bg-teal-100 text-teal-600',
  tabular: 'bg-emerald-100 text-emerald-700',
};

/* ─── Helpers ────────────────────────────────────────────────────────────── */

export function getBackendById(id: string): BackendMeta | undefined {
  return BACKEND_META.find(b => b.id === id);
}

export function getModelById(id: string): ModelEntry | undefined {
  return ALL_MODELS.find(m => m.id === id);
}

export function getModelsByBackend(backendId: string): ModelEntry[] {
  return ALL_MODELS.filter(m => m.backend === backendId);
}

export function getModelCount(backendId: string): number {
  return ALL_MODELS.filter(m => m.backend === backendId).length;
}
