use serde_json::json;

/// Plataforma objetivo para el notebook generado.
#[derive(Debug, Clone, Copy)]
pub enum Platform {
    Colab,
    Kaggle,
    HuggingFace,
    Generic,
}

impl Platform {
    pub fn filename(self) -> &'static str {
        match self {
            Platform::Colab => "colab_train.ipynb",
            Platform::Kaggle => "kaggle_train.ipynb",
            Platform::HuggingFace => "hf_train.ipynb",
            Platform::Generic => "local_train.ipynb",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Platform::Colab => "Google Colab",
            Platform::Kaggle => "Kaggle Notebooks",
            Platform::HuggingFace => "HuggingFace Spaces / local",
            Platform::Generic => "Local / Generic Jupyter",
        }
    }

    pub fn all() -> [Platform; 4] {
        [
            Platform::Colab,
            Platform::Kaggle,
            Platform::HuggingFace,
            Platform::Generic,
        ]
    }
}

/// Converts a Python script + requirements into a Jupyter notebook JSON string
/// tailored to the target platform.
pub fn script_to_notebook(
    platform: Platform,
    title: &str,
    project_name: &str,
    backend: &str,
    model_id: &str,
    task: &str,
    zip_filename: &str,
    requirements: &[&str],
    script_content: &str,
) -> String {
    let mut cells = Vec::new();

    // ── Markdown: branded header ──────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(&format!(
r#"# {title}

> Generated by **Annotix** — professional annotation & training tool.

| Project | Backend | Model | Task | Target |
|---------|---------|-------|------|--------|
| **{project_name}** | `{backend}` | `{model_id}` | `{task}` | **{platform_label}** |

---

{usage}
"#,
            platform_label = platform.label(),
            usage = usage_section(platform, zip_filename),
        ))
    }));

    // ── Code: platform-specific bootstrap ─────────────────────────────────
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": code_lines(&bootstrap_cell(platform, zip_filename))
    }));

    // ── Markdown: install section ─────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines("## Install dependencies\n")
    }));

    // ── Code: pip install ─────────────────────────────────────────────────
    let mut pip_reqs: Vec<String> = requirements.iter().map(|r| (*r).to_string()).collect();
    if matches!(platform, Platform::HuggingFace) {
        pip_reqs.push("huggingface_hub".into());
        pip_reqs.push("datasets".into());
    }
    if !pip_reqs.is_empty() {
        let pip_line = format!("!pip install -q {}\n", pip_reqs.join(" "));
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": [pip_line]
        }));
    }

    // ── HuggingFace: auth + dataset download hooks ────────────────────────
    if matches!(platform, Platform::HuggingFace) {
        cells.push(json!({
            "cell_type": "markdown",
            "metadata": {},
            "source": md_lines(
"## HuggingFace Hub authentication\n\n\
Set `HF_TOKEN` as an environment variable, or paste your token when `login()` prompts you. \
If `HF_DATASET_REPO` is set, the dataset is pulled from the Hub instead of the local zip.\n"
            )
        }));
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": code_lines(HF_AUTH_CELL)
        }));
    }

    // ── Markdown: auto-tune ───────────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(
"## Hardware auto-tune\n\n\
Detects GPU/CPU, picks sensible `batch`, `workers` and `amp` values and injects them into \
training on the fly — **no need to edit `train.py`**.\n"
        )
    }));

    let autotune_cell = build_autotune_cell(backend);
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": code_lines(&autotune_cell)
    }));

    // ── Markdown: training section ────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines("## Training script\n\nEach cell below is a logical block from the generated `train.py`. Run them in order.\n")
    }));

    // ── Code: script blocks ───────────────────────────────────────────────
    let blocks = split_script_blocks(script_content);
    for block in &blocks {
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": code_lines(block)
        }));
    }

    // ── Code: invoke main() ───────────────────────────────────────────────
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": ["main()\n"]
    }));

    // ── Platform-specific: packaging / upload / download ──────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(&format!("## Results and next steps\n\n{}\n", next_steps_md(platform)))
    }));
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": code_lines(&results_cell(platform, backend, project_name, model_id))
    }));

    // ── Markdown: footer ──────────────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(
"---\n\n*Generated by [Annotix](https://github.com/) — annotate, train and export from one app.*\n"
        )
    }));

    let notebook = json!({
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            },
            "annotix": {
                "project": project_name,
                "backend": backend,
                "model": model_id,
                "task": task,
                "platform": platform.label()
            }
        },
        "cells": cells
    });

    serde_json::to_string_pretty(&notebook).unwrap_or_default()
}

fn usage_section(platform: Platform, zip: &str) -> String {
    match platform {
        Platform::Colab => format!(
"## How to use (Colab)\n\n\
1. **Runtime → Change runtime type → GPU** (T4 / L4 / A100).\n\
2. Run the next cell: it will ask you to upload `{zip}`. It auto-extracts.\n\
3. Run the rest of the cells in order.\n\n\
> Colab disconnects idle sessions — keep an eye on training.\n"),
        Platform::Kaggle => format!(
"## How to use (Kaggle)\n\n\
1. Upload `{zip}` as a private **Dataset** and attach it to the notebook (right panel → *Add data*).\n\
2. Turn on GPU: *Settings → Accelerator → GPU T4/P100*.\n\
3. Run the cells in order. Outputs go to `/kaggle/working/`.\n\n\
> GPU quota: ~30 h/week. Warnings when caching labels inside `/kaggle/input/` are expected (read-only).\n"),
        Platform::HuggingFace => format!(
"## How to use (HuggingFace)\n\n\
1. Authenticate with `HF_TOKEN` (env var or `login()`).\n\
2. Optional: set `HF_DATASET_REPO=<user>/<repo>` to pull the dataset from the Hub.\n\
3. Otherwise place `{zip}` next to the notebook and the bootstrap cell extracts it.\n\
4. When training finishes you can upload the weights to the Hub with the final cell.\n"),
        Platform::Generic => format!(
"## How to use (local / generic)\n\n\
1. Place `{zip}` next to the notebook (or extract it beforehand — `dataset/` must exist).\n\
2. Run the cells in order.\n\
3. Device is auto-detected: CUDA / MPS / CPU.\n\n\
> CPU-only = very slow training, use it only for smoke-tests.\n"),
    }
}

fn bootstrap_cell(platform: Platform, zip: &str) -> String {
    match platform {
        Platform::Colab => format!(
r#"# Annotix bootstrap — Colab
import os, zipfile, sys

def _annotix_bootstrap(expected_zip="{zip}"):
    if os.path.isdir("dataset"):
        print("[annotix] dataset/ already present — skipping bootstrap")
        return
    in_colab = "google.colab" in sys.modules or os.environ.get("COLAB_RELEASE_TAG")
    if in_colab:
        from google.colab import files  # type: ignore
        print(f"[annotix] upload the training package ZIP (expected: {{expected_zip}})")
        uploaded = files.upload()
        zip_name = next((n for n in uploaded if n.endswith(".zip")), None)
        if zip_name is None:
            raise RuntimeError("No .zip uploaded")
        with zipfile.ZipFile(zip_name) as z:
            z.extractall(".")
        print(f"[annotix] extracted {{zip_name}}")
    elif os.path.exists(expected_zip):
        with zipfile.ZipFile(expected_zip) as z:
            z.extractall(".")
        print(f"[annotix] extracted {{expected_zip}}")
    else:
        raise FileNotFoundError(f"{{expected_zip}} not found and dataset/ does not exist")

_annotix_bootstrap()
"#),
        Platform::Kaggle => format!(
r#"# Annotix bootstrap — Kaggle
# Looks for the .zip package (or already-extracted folder) inside /kaggle/input/
import os, zipfile, glob, shutil

WORK = "/kaggle/working"
os.chdir(WORK)

if not os.path.isdir("dataset"):
    # 1) a Kaggle Dataset carrying the zip
    candidates = glob.glob("/kaggle/input/**/{zip}", recursive=True)
    if candidates:
        print(f"[annotix] found zip: {{candidates[0]}}")
        with zipfile.ZipFile(candidates[0]) as z:
            z.extractall(".")
    else:
        # 2) dataset may already be extracted: look for data.yaml
        yamls = glob.glob("/kaggle/input/**/data.yaml", recursive=True)
        if yamls:
            src = os.path.dirname(yamls[0])
            print(f"[annotix] copying pre-extracted dataset from {{src}}")
            shutil.copytree(src, os.path.join(WORK, "dataset"), dirs_exist_ok=True)
        else:
            raise FileNotFoundError(
                "Neither {zip} nor data.yaml found under /kaggle/input/. "
                "Upload the package as a Dataset and attach it to the notebook."
            )
else:
    print("[annotix] dataset/ already present")
print("[annotix] cwd:", os.getcwd())
"#),
        Platform::HuggingFace => format!(
r#"# Annotix bootstrap — HuggingFace / local
# If HF_DATASET_REPO is set, pulls the dataset from the Hub.
# Otherwise expects {zip} next to the notebook.
import os, zipfile

HF_DATASET_REPO = os.environ.get("HF_DATASET_REPO", "").strip()

if os.path.isdir("dataset"):
    print("[annotix] dataset/ already present — skipping bootstrap")
elif HF_DATASET_REPO:
    from huggingface_hub import snapshot_download
    print(f"[annotix] downloading dataset from {{HF_DATASET_REPO}}")
    local = snapshot_download(repo_id=HF_DATASET_REPO, repo_type="dataset", local_dir="dataset")
    print(f"[annotix] dataset at {{local}}")
elif os.path.exists("{zip}"):
    with zipfile.ZipFile("{zip}") as z:
        z.extractall(".")
    print(f"[annotix] extracted {zip}")
else:
    raise FileNotFoundError(
        "No dataset/, no HF_DATASET_REPO, and no {zip} next to the notebook."
    )
"#),
        Platform::Generic => format!(
r#"# Annotix bootstrap — local / generic
import os, zipfile
from pathlib import Path

HERE = Path.cwd()
ZIP = HERE / "{zip}"

if (HERE / "dataset").is_dir():
    print("[annotix] dataset/ already present — skipping bootstrap")
elif ZIP.exists():
    with zipfile.ZipFile(ZIP) as z:
        z.extractall(HERE)
    print(f"[annotix] extracted {{ZIP.name}}")
else:
    raise FileNotFoundError(
        f"Neither dataset/ nor {{ZIP.name}} exists in {{HERE}}. "
        "Place the zip next to the notebook or extract it beforehand."
    )

# Minimal validation
required = [HERE / "dataset" / "data.yaml"]
missing = [p for p in required if not p.exists()]
if missing:
    print(f"[annotix] warning: missing paths {{missing}} — check the package")
"#),
    }
}

const HF_AUTH_CELL: &str = r#"# HuggingFace auth (token from HF_TOKEN env var or interactive login)
import os
try:
    from huggingface_hub import login, HfApi
    token = os.environ.get("HF_TOKEN")
    if token:
        login(token=token, add_to_git_credential=False)
        print("[annotix] HF login OK (env)")
    else:
        login()  # prompts for token
except Exception as e:
    print(f"[annotix] HF login skipped: {e}")
"#;

fn next_steps_md(platform: Platform) -> &'static str {
    match platform {
        Platform::Colab =>
"Artifacts land in `dataset/train/` (weights, metrics, curves). \
Run the next cell to bundle and download them.",
        Platform::Kaggle =>
"Artifacts land in `/kaggle/working/`. When the session ends they show up in the notebook's *Output* panel.",
        Platform::HuggingFace =>
"Artifacts land in `dataset/train/`. The next cell can push them to the Hub if you set `HF_MODEL_REPO`.",
        Platform::Generic =>
"Artifacts land in `dataset/train/` next to the notebook.",
    }
}

fn results_cell(platform: Platform, backend: &str, project_name: &str, model_id: &str) -> String {
    let is_ultralytics = matches!(backend, "YOLO" | "RT-DETR" | "yolo" | "rt_detr");
    let work_root = match platform {
        Platform::Kaggle => "/kaggle/working",
        _ => ".",
    };
    let download_block = match platform {
        Platform::Colab => r#"
try:
    from google.colab import files  # type: ignore
    files.download(full_zip)
    files.download(weights_zip)
except Exception as _e:
    print(f"[annotix] auto-download skipped: {_e}")
"#,
        Platform::Kaggle => r#"
print("\n📥 Download the zips from the Notebook 'Output' panel after the session ends.")
"#,
        Platform::HuggingFace => r#"
import os as _os
HF_MODEL_REPO = _os.environ.get("HF_MODEL_REPO", "").strip()
if HF_MODEL_REPO:
    try:
        from huggingface_hub import HfApi, create_repo
        api = HfApi()
        create_repo(HF_MODEL_REPO, repo_type="model", exist_ok=True)
        api.upload_folder(folder_path=OUTPUT_DIR, repo_id=HF_MODEL_REPO, repo_type="model")
        print(f"\n✅ Uploaded release folder to https://huggingface.co/{HF_MODEL_REPO}")
    except Exception as _e:
        print(f"[annotix] HF upload failed: {_e}")
else:
    print("\n[annotix] HF_MODEL_REPO not set — release zips remain local.")
"#,
        Platform::Generic => "",
    };

    if !is_ultralytics {
        // Backends que no son ultralytics: empaquetado simple
        return format!(
            r##"# ============================================================
# Annotix · paquete de release
# ============================================================
import os, shutil, glob, json
from pathlib import Path

WORK_ROOT = "{work_root}"
RUN_GLOB = sorted(glob.glob(os.path.join(WORK_ROOT, "dataset/**/weights"), recursive=True))
RUN_DIR = os.path.dirname(RUN_GLOB[0]) if RUN_GLOB else os.path.join(WORK_ROOT, "dataset")
OUTPUT_DIR = os.path.join(WORK_ROOT, "annotix_release")
if os.path.exists(OUTPUT_DIR):
    shutil.rmtree(OUTPUT_DIR)
shutil.copytree(RUN_DIR, OUTPUT_DIR)

readme = """# {project_name} — {backend} ({model_id})

Modelo entrenado con Annotix.
"""
with open(os.path.join(OUTPUT_DIR, "README.md"), "w") as f:
    f.write(readme)

full_zip = shutil.make_archive(os.path.join(WORK_ROOT, "annotix_release_FULL"), "zip", OUTPUT_DIR)
weights_zip = full_zip  # mismo paquete
print(f"📦 {{full_zip}} ({{os.path.getsize(full_zip)/1e6:.1f}} MB)")
{download_block}
"##,
            work_root = work_root,
            project_name = project_name,
            backend = backend,
            model_id = model_id,
            download_block = download_block,
        );
    }

    // Ultralytics (YOLO / RT-DETR): celda completa estilo "release"
    let project_safe = sanitize_for_path(project_name);
    format!(
        r##"# ============================================================
# Annotix · CELDA FINAL: validar, exportar ONNX, probar y empaquetar
# ============================================================
import os, shutil, json, time, glob
from pathlib import Path

WORK_ROOT = "{work_root}"
PROJECT_NAME = "{project_safe}"
MODEL_ID = "{model_id}"

# Localizar run dir generado por ultralytics (project=dataset, name=train)
_run_candidates = sorted(glob.glob(os.path.join(WORK_ROOT, "dataset/**/weights"), recursive=True))
RUN_DIR = os.path.dirname(_run_candidates[0]) if _run_candidates else os.path.join(WORK_ROOT, "dataset", "train")
BEST_PT = os.path.join(RUN_DIR, "weights", "best.pt")
LAST_PT = os.path.join(RUN_DIR, "weights", "last.pt")
DATA_YAML = os.path.join(WORK_ROOT, "dataset", "data.yaml")

OUTPUT_DIR = os.path.join(WORK_ROOT, f"{{PROJECT_NAME}}_release")
if os.path.exists(OUTPUT_DIR):
    shutil.rmtree(OUTPUT_DIR)
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Determinar imgsz desde args.yaml si existe
EXPORT_IMGSZ = 640
_args_yaml = os.path.join(RUN_DIR, "args.yaml")
if os.path.exists(_args_yaml):
    try:
        import yaml as _yaml
        with open(_args_yaml) as _f:
            _args = _yaml.safe_load(_f) or {{}}
        EXPORT_IMGSZ = int(_args.get("imgsz", 640))
    except Exception:
        pass

print("="*60)
print("PASO 1: Validar best.pt en val (y test si existe)")
print("="*60)

from ultralytics import YOLO
model = YOLO(BEST_PT)

def _collect_metrics(res):
    if res is None or not hasattr(res, "box"):
        return None
    b = res.box
    out = {{
        "global": {{
            "precision": float(getattr(b, "mp", float("nan"))),
            "recall":    float(getattr(b, "mr", float("nan"))),
            "mAP50":     float(getattr(b, "map50", float("nan"))),
            "mAP50-95":  float(getattr(b, "map", float("nan"))),
        }},
        "per_class": {{}},
    }}
    try:
        for i, name in model.names.items():
            out["per_class"][name] = {{
                "precision": float(b.p[i]),
                "recall":    float(b.r[i]),
                "mAP50":     float(b.ap50[i]),
                "mAP50-95":  float(b.ap[i]),
            }}
    except Exception:
        pass
    return out

val_metrics = None
test_metrics = None
try:
    val_results = model.val(data=DATA_YAML, imgsz=EXPORT_IMGSZ, verbose=False)
    val_metrics = _collect_metrics(val_results)
    print(f"✅ val mAP50: {{val_metrics['global']['mAP50']:.4f}}  mAP50-95: {{val_metrics['global']['mAP50-95']:.4f}}")
except Exception as _e:
    print(f"⚠️  val falló: {{_e}}")

try:
    import yaml as _yaml
    with open(DATA_YAML) as _f:
        _yd = _yaml.safe_load(_f) or {{}}
    if _yd.get("test"):
        test_results = model.val(data=DATA_YAML, split="test", imgsz=EXPORT_IMGSZ, verbose=False)
        test_metrics = _collect_metrics(test_results)
        if test_metrics:
            print(f"✅ test mAP50: {{test_metrics['global']['mAP50']:.4f}}  mAP50-95: {{test_metrics['global']['mAP50-95']:.4f}}")
    else:
        print("ℹ️  No hay split 'test' declarado en data.yaml — se omite")
except Exception as _e:
    print(f"⚠️  test eval skipped: {{_e}}")

metrics_summary = {{
    "project":     PROJECT_NAME,
    "model":       MODEL_ID,
    "imgsz":       EXPORT_IMGSZ,
    "num_classes": len(model.names),
    "class_names": list(model.names.values()),
    "val":         val_metrics,
    "test":        test_metrics,
}}
with open(os.path.join(OUTPUT_DIR, "metrics.json"), "w") as f:
    json.dump(metrics_summary, f, indent=2)

print("\n" + "="*60)
print("PASO 2: Exportar a ONNX")
print("="*60)

onnx_path = None
try:
    onnx_path = model.export(format="onnx", imgsz=EXPORT_IMGSZ, simplify=True, opset=12, dynamic=False, half=False)
    print(f"✅ ONNX exportado: {{onnx_path}}  ({{os.path.getsize(onnx_path)/1e6:.2f}} MB)")
except Exception as _e:
    print(f"⚠️  Export ONNX falló: {{_e}}")

print("\n" + "="*60)
print("PASO 3: Validar ONNX y benchmark inferencia")
print("="*60)

if onnx_path and os.path.exists(onnx_path):
    try:
        import onnx as _onnx
        _m = _onnx.load(onnx_path)
        _onnx.checker.check_model(_m)
        i0 = _m.graph.input[0]; o0 = _m.graph.output[0]
        print(f"✅ ONNX válido — input {{i0.name}}={{[d.dim_value for d in i0.type.tensor_type.shape.dim]}}  output {{o0.name}}={{[d.dim_value for d in o0.type.tensor_type.shape.dim]}}")
    except Exception as _e:
        print(f"⚠️  ONNX checker: {{_e}}")
    try:
        import onnxruntime as _ort, numpy as _np
        _sess = _ort.InferenceSession(onnx_path, providers=['CUDAExecutionProvider', 'CPUExecutionProvider'])
        _in = _sess.get_inputs()[0].name
        _x = _np.random.randn(1, 3, EXPORT_IMGSZ, EXPORT_IMGSZ).astype(_np.float32)
        for _ in range(3): _sess.run(None, {{_in: _x}})
        _t = time.perf_counter()
        for _ in range(10): _o = _sess.run(None, {{_in: _x}})
        _ms = (time.perf_counter() - _t) / 10 * 1000
        print(f"✅ ORT provider={{_sess.get_providers()[0]}}  ~{{_ms:.2f}} ms/img  out={{_o[0].shape}}")
    except Exception as _e:
        print(f"⚠️  onnxruntime: {{_e}}")

print("\n" + "="*60)
print("PASO 4: Comparativa PT vs ONNX en una imagen real")
print("="*60)

_split_dirs = [os.path.join(WORK_ROOT, "dataset", "images", s) for s in ("test", "val")]
_test_image = None
for _d in _split_dirs:
    if os.path.isdir(_d):
        _imgs = [f for f in os.listdir(_d) if f.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp', '.webp'))]
        if _imgs:
            _test_image = os.path.join(_d, _imgs[0])
            break
if _test_image:
    try:
        _pt = YOLO(BEST_PT).predict(_test_image, imgsz=EXPORT_IMGSZ, conf=0.25, verbose=False)[0]
        _pt_n = len(_pt.boxes) if _pt.boxes is not None else 0
        _on_n = "n/a"
        if onnx_path and os.path.exists(onnx_path):
            _on = YOLO(onnx_path).predict(_test_image, imgsz=EXPORT_IMGSZ, conf=0.25, verbose=False)[0]
            _on_n = len(_on.boxes) if _on.boxes is not None else 0
        print(f"   imagen: {{os.path.basename(_test_image)}}  detecciones PT={{_pt_n}}  ONNX={{_on_n}}")
        try:
            import cv2 as _cv2
            _cv2.imwrite(os.path.join(OUTPUT_DIR, "prediction_example.jpg"), _pt.plot())
            print("   ✅ prediction_example.jpg guardado")
        except Exception:
            pass
    except Exception as _e:
        print(f"⚠️  comparativa: {{_e}}")
else:
    print("ℹ️  No se encontró imagen de val/test para comparar")

print("\n" + "="*60)
print("PASO 5: Copiar pesos, gráficos y data.yaml a release/")
print("="*60)

for _src, _name in [(BEST_PT, "best.pt"), (LAST_PT, "last.pt"), (onnx_path, "best.onnx")]:
    if _src and os.path.exists(_src):
        shutil.copy(_src, os.path.join(OUTPUT_DIR, _name))
        print(f"   + {{_name}}")

for _p in ["results.png", "results.csv", "confusion_matrix.png", "confusion_matrix_normalized.png",
           "F1_curve.png", "PR_curve.png", "P_curve.png", "R_curve.png", "labels.jpg", "labels_correlogram.jpg", "args.yaml"]:
    _src = os.path.join(RUN_DIR, _p)
    if os.path.exists(_src):
        shutil.copy(_src, os.path.join(OUTPUT_DIR, _p))

if os.path.exists(DATA_YAML):
    shutil.copy(DATA_YAML, os.path.join(OUTPUT_DIR, "data.yaml"))

_param_count = sum(p.numel() for p in model.model.parameters())
_class_lines = "\n".join([f"- {{i}}: {{n}}" for i, n in model.names.items()])
_val_md = "n/a" if not val_metrics else (
    f"- mAP50: **{{val_metrics['global']['mAP50']:.4f}}**\n"
    f"- mAP50-95: **{{val_metrics['global']['mAP50-95']:.4f}}**\n"
    f"- precision: {{val_metrics['global']['precision']:.4f}} / recall: {{val_metrics['global']['recall']:.4f}}"
)
_test_md = "" if not test_metrics else (
    f"\n\n## Métricas (test)\n"
    f"- mAP50: **{{test_metrics['global']['mAP50']:.4f}}**\n"
    f"- mAP50-95: **{{test_metrics['global']['mAP50-95']:.4f}}**\n"
    f"- precision: {{test_metrics['global']['precision']:.4f}} / recall: {{test_metrics['global']['recall']:.4f}}"
)

_readme = f"""# {{PROJECT_NAME}} · {{MODEL_ID}}

Modelo entrenado con **Annotix**.

## Configuración
- Modelo base: `{{MODEL_ID}}` ({{_param_count:,}} parámetros)
- Tamaño entrada: {{EXPORT_IMGSZ}}x{{EXPORT_IMGSZ}}
- Clases ({{len(model.names)}}):
{{_class_lines}}

## Métricas (val)
{{_val_md}}{{_test_md}}

## Archivos
- `best.pt` / `last.pt` — checkpoints PyTorch
- `best.onnx` — modelo exportado a ONNX (deployment)
- `metrics.json` — métricas detalladas por clase (val + test)
- `data.yaml` — config dataset
- `results.csv` / `results.png` — log de entrenamiento
- `*_curve.png`, `confusion_matrix*.png` — gráficos
- `prediction_example.jpg` — predicción de ejemplo

## Uso
```python
from ultralytics import YOLO
model = YOLO("best.pt")  # o "best.onnx"
results = model.predict("img.jpg", conf=0.25)
```
"""
with open(os.path.join(OUTPUT_DIR, "README.md"), "w") as f:
    f.write(_readme)

print("\n" + "="*60)
print("PASO 6: Crear ZIPs (full + weights-only)")
print("="*60)

full_zip = shutil.make_archive(os.path.join(WORK_ROOT, f"{{PROJECT_NAME}}_FULL"), "zip", OUTPUT_DIR)
print(f"📦 {{os.path.basename(full_zip)}}  ({{os.path.getsize(full_zip)/1e6:.1f}} MB)  — pesos + gráficos + métricas")

_w_dir = os.path.join(WORK_ROOT, f"{{PROJECT_NAME}}_weights_only")
if os.path.exists(_w_dir):
    shutil.rmtree(_w_dir)
os.makedirs(_w_dir)
for _f in ["best.pt", "best.onnx", "metrics.json", "README.md", "data.yaml"]:
    _src = os.path.join(OUTPUT_DIR, _f)
    if os.path.exists(_src):
        shutil.copy(_src, os.path.join(_w_dir, _f))
weights_zip = shutil.make_archive(os.path.join(WORK_ROOT, f"{{PROJECT_NAME}}_weights_only"), "zip", _w_dir)
print(f"📦 {{os.path.basename(weights_zip)}}  ({{os.path.getsize(weights_zip)/1e6:.1f}} MB)  — solo deployment")

print("\n" + "="*60)
print("MÉTRICAS POR CLASE")
print("="*60)
print(f"{{'Clase':<28}} {{'P':<8}} {{'R':<8}} {{'mAP50':<8}} {{'mAP50-95':<10}}")
print("-" * 70)
_per_class = (val_metrics or {{}}).get("per_class", {{}})
for _n, _m in _per_class.items():
    print(f"{{_n:<28}} {{_m['precision']:<8.3f}} {{_m['recall']:<8.3f}} {{_m['mAP50']:<8.3f}} {{_m['mAP50-95']:<10.3f}}")
if val_metrics:
    _g = val_metrics["global"]
    print("-" * 70)
    print(f"{{'GLOBAL (val)':<28}} {{_g['precision']:<8.3f}} {{_g['recall']:<8.3f}} {{_g['mAP50']:<8.3f}} {{_g['mAP50-95']:<10.3f}}")
if test_metrics:
    _g = test_metrics["global"]
    print(f"{{'GLOBAL (test)':<28}} {{_g['precision']:<8.3f}} {{_g['recall']:<8.3f}} {{_g['mAP50']:<8.3f}} {{_g['mAP50-95']:<10.3f}}")
{download_block}
print("\n✅ Listo. Release en:", OUTPUT_DIR)
"##,
        work_root = work_root,
        project_safe = project_safe,
        model_id = model_id,
        download_block = download_block,
    )
}

fn sanitize_for_path(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
            out.push(c);
        } else if c.is_whitespace() {
            out.push('_');
        }
    }
    if out.is_empty() { "annotix_project".to_string() } else { out }
}

/// Genera la celda de auto-tune: detecta GPU/CPU, elige batch/workers/amp
/// según VRAM y, para backends basados en ultralytics (YOLO / RT-DETR),
/// parchea `YOLO.train` / `RTDETR.train` para inyectar los overrides sin
/// tener que editar el `train.py` generado.
fn build_autotune_cell(backend: &str) -> String {
    let patch_block = match backend {
        "YOLO" | "RT-DETR" => r#"
# Monkey-patch ultralytics para aplicar overrides sin tocar train.py
try:
    from ultralytics import YOLO as _AnnotixYOLO
    _orig_yolo_train = _AnnotixYOLO.train
    def _annotix_yolo_train(self, **kwargs):
        kwargs["device"]  = os.environ["ANNOTIX_DEVICE"]
        kwargs["batch"]   = int(os.environ["ANNOTIX_BATCH"])
        kwargs["workers"] = int(os.environ["ANNOTIX_WORKERS"])
        kwargs["amp"]     = os.environ["ANNOTIX_AMP"] == "1"
        print(f"[annotix] YOLO.train overrides → device={kwargs['device']} "
              f"batch={kwargs['batch']} workers={kwargs['workers']} amp={kwargs['amp']}")
        return _orig_yolo_train(self, **kwargs)
    _AnnotixYOLO.train = _annotix_yolo_train
except Exception as _e:
    print(f"[annotix] YOLO patch skipped: {_e}")

try:
    from ultralytics import RTDETR as _AnnotixRTDETR
    _orig_rtdetr_train = _AnnotixRTDETR.train
    def _annotix_rtdetr_train(self, **kwargs):
        kwargs["device"]  = os.environ["ANNOTIX_DEVICE"]
        kwargs["batch"]   = int(os.environ["ANNOTIX_BATCH"])
        kwargs["workers"] = int(os.environ["ANNOTIX_WORKERS"])
        kwargs["amp"]     = os.environ["ANNOTIX_AMP"] == "1"
        return _orig_rtdetr_train(self, **kwargs)
    _AnnotixRTDETR.train = _annotix_rtdetr_train
except Exception:
    pass
"#,
        _ => r#"
# For this backend overrides are exposed via env vars
# (ANNOTIX_DEVICE / ANNOTIX_BATCH / ANNOTIX_WORKERS / ANNOTIX_AMP).
"#,
    };

    format!(
r#"# Annotix · hardware auto-tune
import os, multiprocessing

try:
    import torch
    _has_cuda = torch.cuda.is_available()
    _has_mps = getattr(torch.backends, "mps", None) and torch.backends.mps.is_available()
except Exception:
    torch = None
    _has_cuda = False
    _has_mps = False

if _has_cuda:
    _name = torch.cuda.get_device_name(0)
    _props = torch.cuda.get_device_properties(0)
    _vram_gb = _props.total_memory / (1024 ** 3)
    _cc = f"{{_props.major}}.{{_props.minor}}"
    print(f"[annotix] GPU: {{_name}} · {{_vram_gb:.1f}} GB · CC {{_cc}}")

    if _vram_gb >= 70:       # H100 80, A100 80
        _batch = 96
    elif _vram_gb >= 38:     # A100 40
        _batch = 64
    elif _vram_gb >= 22:     # L4 24, 3090, 4090
        _batch = 32
    elif _vram_gb >= 14:     # T4 16, V100 16, P100 16
        _batch = 16
    elif _vram_gb >= 10:
        _batch = 12
    else:
        _batch = 8

    _device = "0"
    _workers = 4
    _amp = _props.major >= 7
elif _has_mps:
    print("[annotix] Apple Silicon MPS detected")
    _device = "mps"
    _batch = 8
    _workers = 2
    _amp = False
else:
    print("[annotix] no GPU — falling back to CPU (training will be slow)")
    _device = "cpu"
    _batch = 8
    _workers = max(2, multiprocessing.cpu_count() // 2)
    _amp = False

os.environ["ANNOTIX_DEVICE"]  = os.environ.get("ANNOTIX_DEVICE",  _device)
os.environ["ANNOTIX_BATCH"]   = os.environ.get("ANNOTIX_BATCH",   str(_batch))
os.environ["ANNOTIX_WORKERS"] = os.environ.get("ANNOTIX_WORKERS", str(_workers))
os.environ["ANNOTIX_AMP"]     = os.environ.get("ANNOTIX_AMP",     "1" if _amp else "0")

print(f"[annotix] tuned → device={{os.environ['ANNOTIX_DEVICE']}} "
      f"batch={{os.environ['ANNOTIX_BATCH']}} "
      f"workers={{os.environ['ANNOTIX_WORKERS']}} "
      f"amp={{os.environ['ANNOTIX_AMP']}}")
{patch_block}"#,
        patch_block = patch_block,
    )
}

fn md_lines(s: &str) -> Vec<String> {
    s.lines().map(|l| format!("{}\n", l)).collect()
}

fn code_lines(s: &str) -> Vec<String> {
    s.lines().map(|l| format!("{}\n", l)).collect()
}

fn split_script_blocks(script: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut current = String::new();

    for line in script.lines() {
        if (line.starts_with("def ") || line.starts_with("class ") || line.starts_with("if __name__"))
            && !current.trim().is_empty()
        {
            blocks.push(current.trim().to_string());
            current = String::new();
        }
        if line.starts_with("#!") {
            continue;
        }
        current.push_str(line);
        current.push('\n');
    }

    if !current.trim().is_empty() {
        let trimmed = current.trim();
        if !trimmed.contains("if __name__") {
            blocks.push(trimmed.to_string());
        }
    }

    if blocks.is_empty() {
        blocks.push(script.to_string());
    }

    blocks
}
