use serde_json::json;

/// Converts a Python script + requirements into a Jupyter notebook JSON string
pub fn script_to_notebook(
    title: &str,
    description: &str,
    requirements: &[&str],
    script_content: &str,
) -> String {
    let mut cells = Vec::new();

    // Markdown cell: title
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            format!("# {}\n", title),
            format!("{}\n", description),
            "\n",
            "Generated by **Annotix** — Professional Annotation Tool\n"
        ]
    }));

    // Code cell: install requirements
    if !requirements.is_empty() {
        let pip_line = format!("!pip install {}\n", requirements.join(" "));
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": [pip_line]
        }));
    }

    // Split script into logical blocks (at top-level function definitions and imports)
    let blocks = split_script_blocks(script_content);
    for block in &blocks {
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": block.lines().map(|l| format!("{}\n", l)).collect::<Vec<_>>()
        }));
    }

    // Final cell: run
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": ["main()\n"]
    }));

    let notebook = json!({
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            }
        },
        "cells": cells
    });

    serde_json::to_string_pretty(&notebook).unwrap_or_default()
}

fn split_script_blocks(script: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut current = String::new();

    for line in script.lines() {
        // Start new block at top-level def/class or 'if __name__'
        if (line.starts_with("def ") || line.starts_with("class ") || line.starts_with("if __name__"))
            && !current.trim().is_empty()
        {
            blocks.push(current.trim().to_string());
            current = String::new();
        }
        // Skip shebang and module docstrings
        if line.starts_with("#!") {
            continue;
        }
        current.push_str(line);
        current.push('\n');
    }

    if !current.trim().is_empty() {
        // Remove the `if __name__ == "__main__": main()` block
        let trimmed = current.trim();
        if !trimmed.contains("if __name__") {
            blocks.push(trimmed.to_string());
        }
    }

    // If we got nothing, just push the whole thing
    if blocks.is_empty() {
        blocks.push(script.to_string());
    }

    blocks
}
