use serde_json::json;

/// Plataforma objetivo para el notebook generado.
#[derive(Debug, Clone, Copy)]
pub enum Platform {
    Colab,
    Kaggle,
    HuggingFace,
    Generic,
}

impl Platform {
    pub fn filename(self) -> &'static str {
        match self {
            Platform::Colab => "colab_train.ipynb",
            Platform::Kaggle => "kaggle_train.ipynb",
            Platform::HuggingFace => "hf_train.ipynb",
            Platform::Generic => "local_train.ipynb",
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Platform::Colab => "Google Colab",
            Platform::Kaggle => "Kaggle Notebooks",
            Platform::HuggingFace => "HuggingFace Spaces / local",
            Platform::Generic => "Local / Generic Jupyter",
        }
    }

    pub fn all() -> [Platform; 4] {
        [
            Platform::Colab,
            Platform::Kaggle,
            Platform::HuggingFace,
            Platform::Generic,
        ]
    }
}

/// Converts a Python script + requirements into a Jupyter notebook JSON string
/// tailored to the target platform.
pub fn script_to_notebook(
    platform: Platform,
    title: &str,
    project_name: &str,
    backend: &str,
    model_id: &str,
    task: &str,
    zip_filename: &str,
    requirements: &[&str],
    script_content: &str,
) -> String {
    let mut cells = Vec::new();

    // ── Markdown: branded header ──────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(&format!(
r#"# {title}

> Generated by **Annotix** — professional annotation & training tool.

| Project | Backend | Model | Task | Target |
|---------|---------|-------|------|--------|
| **{project_name}** | `{backend}` | `{model_id}` | `{task}` | **{platform_label}** |

---

{usage}
"#,
            platform_label = platform.label(),
            usage = usage_section(platform, zip_filename),
        ))
    }));

    // ── Code: platform-specific bootstrap ─────────────────────────────────
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": code_lines(&bootstrap_cell(platform, zip_filename))
    }));

    // ── Markdown: install section ─────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines("## Install dependencies\n")
    }));

    // ── Code: pip install ─────────────────────────────────────────────────
    let mut pip_reqs: Vec<String> = requirements.iter().map(|r| (*r).to_string()).collect();
    if matches!(platform, Platform::HuggingFace) {
        pip_reqs.push("huggingface_hub".into());
        pip_reqs.push("datasets".into());
    }
    if !pip_reqs.is_empty() {
        let pip_line = format!("!pip install -q {}\n", pip_reqs.join(" "));
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": [pip_line]
        }));
    }

    // ── HuggingFace: auth + dataset download hooks ────────────────────────
    if matches!(platform, Platform::HuggingFace) {
        cells.push(json!({
            "cell_type": "markdown",
            "metadata": {},
            "source": md_lines(
"## HuggingFace Hub authentication\n\n\
Set `HF_TOKEN` as an environment variable, or paste your token when `login()` prompts you. \
If `HF_DATASET_REPO` is set, the dataset is pulled from the Hub instead of the local zip.\n"
            )
        }));
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": code_lines(HF_AUTH_CELL)
        }));
    }

    // ── Markdown: auto-tune ───────────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(
"## Hardware auto-tune\n\n\
Detects GPU/CPU, picks sensible `batch`, `workers` and `amp` values and injects them into \
training on the fly — **no need to edit `train.py`**.\n"
        )
    }));

    let autotune_cell = build_autotune_cell(backend);
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": code_lines(&autotune_cell)
    }));

    // ── Markdown: training section ────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines("## Training script\n\nEach cell below is a logical block from the generated `train.py`. Run them in order.\n")
    }));

    // ── Code: script blocks ───────────────────────────────────────────────
    let blocks = split_script_blocks(script_content);
    for block in &blocks {
        cells.push(json!({
            "cell_type": "code",
            "execution_count": null,
            "metadata": {},
            "outputs": [],
            "source": code_lines(block)
        }));
    }

    // ── Code: invoke main() ───────────────────────────────────────────────
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": ["main()\n"]
    }));

    // ── Platform-specific: packaging / upload / download ──────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(&format!("## Results and next steps\n\n{}\n", next_steps_md(platform)))
    }));
    cells.push(json!({
        "cell_type": "code",
        "execution_count": null,
        "metadata": {},
        "outputs": [],
        "source": code_lines(&results_cell(platform))
    }));

    // ── Markdown: footer ──────────────────────────────────────────────────
    cells.push(json!({
        "cell_type": "markdown",
        "metadata": {},
        "source": md_lines(
"---\n\n*Generated by [Annotix](https://github.com/) — annotate, train and export from one app.*\n"
        )
    }));

    let notebook = json!({
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.10.0"
            },
            "annotix": {
                "project": project_name,
                "backend": backend,
                "model": model_id,
                "task": task,
                "platform": platform.label()
            }
        },
        "cells": cells
    });

    serde_json::to_string_pretty(&notebook).unwrap_or_default()
}

fn usage_section(platform: Platform, zip: &str) -> String {
    match platform {
        Platform::Colab => format!(
"## How to use (Colab)\n\n\
1. **Runtime → Change runtime type → GPU** (T4 / L4 / A100).\n\
2. Run the next cell: it will ask you to upload `{zip}`. It auto-extracts.\n\
3. Run the rest of the cells in order.\n\n\
> Colab disconnects idle sessions — keep an eye on training.\n"),
        Platform::Kaggle => format!(
"## How to use (Kaggle)\n\n\
1. Upload `{zip}` as a private **Dataset** and attach it to the notebook (right panel → *Add data*).\n\
2. Turn on GPU: *Settings → Accelerator → GPU T4/P100*.\n\
3. Run the cells in order. Outputs go to `/kaggle/working/`.\n\n\
> GPU quota: ~30 h/week. Warnings when caching labels inside `/kaggle/input/` are expected (read-only).\n"),
        Platform::HuggingFace => format!(
"## How to use (HuggingFace)\n\n\
1. Authenticate with `HF_TOKEN` (env var or `login()`).\n\
2. Optional: set `HF_DATASET_REPO=<user>/<repo>` to pull the dataset from the Hub.\n\
3. Otherwise place `{zip}` next to the notebook and the bootstrap cell extracts it.\n\
4. When training finishes you can upload the weights to the Hub with the final cell.\n"),
        Platform::Generic => format!(
"## How to use (local / generic)\n\n\
1. Place `{zip}` next to the notebook (or extract it beforehand — `dataset/` must exist).\n\
2. Run the cells in order.\n\
3. Device is auto-detected: CUDA / MPS / CPU.\n\n\
> CPU-only = very slow training, use it only for smoke-tests.\n"),
    }
}

fn bootstrap_cell(platform: Platform, zip: &str) -> String {
    match platform {
        Platform::Colab => format!(
r#"# Annotix bootstrap — Colab
import os, zipfile, sys

def _annotix_bootstrap(expected_zip="{zip}"):
    if os.path.isdir("dataset"):
        print("[annotix] dataset/ already present — skipping bootstrap")
        return
    in_colab = "google.colab" in sys.modules or os.environ.get("COLAB_RELEASE_TAG")
    if in_colab:
        from google.colab import files  # type: ignore
        print(f"[annotix] upload the training package ZIP (expected: {{expected_zip}})")
        uploaded = files.upload()
        zip_name = next((n for n in uploaded if n.endswith(".zip")), None)
        if zip_name is None:
            raise RuntimeError("No .zip uploaded")
        with zipfile.ZipFile(zip_name) as z:
            z.extractall(".")
        print(f"[annotix] extracted {{zip_name}}")
    elif os.path.exists(expected_zip):
        with zipfile.ZipFile(expected_zip) as z:
            z.extractall(".")
        print(f"[annotix] extracted {{expected_zip}}")
    else:
        raise FileNotFoundError(f"{{expected_zip}} not found and dataset/ does not exist")

_annotix_bootstrap()
"#),
        Platform::Kaggle => format!(
r#"# Annotix bootstrap — Kaggle
# Looks for the .zip package (or already-extracted folder) inside /kaggle/input/
import os, zipfile, glob, shutil

WORK = "/kaggle/working"
os.chdir(WORK)

if not os.path.isdir("dataset"):
    # 1) a Kaggle Dataset carrying the zip
    candidates = glob.glob("/kaggle/input/**/{zip}", recursive=True)
    if candidates:
        print(f"[annotix] found zip: {{candidates[0]}}")
        with zipfile.ZipFile(candidates[0]) as z:
            z.extractall(".")
    else:
        # 2) dataset may already be extracted: look for data.yaml
        yamls = glob.glob("/kaggle/input/**/data.yaml", recursive=True)
        if yamls:
            src = os.path.dirname(yamls[0])
            print(f"[annotix] copying pre-extracted dataset from {{src}}")
            shutil.copytree(src, os.path.join(WORK, "dataset"), dirs_exist_ok=True)
        else:
            raise FileNotFoundError(
                "Neither {zip} nor data.yaml found under /kaggle/input/. "
                "Upload the package as a Dataset and attach it to the notebook."
            )
else:
    print("[annotix] dataset/ already present")
print("[annotix] cwd:", os.getcwd())
"#),
        Platform::HuggingFace => format!(
r#"# Annotix bootstrap — HuggingFace / local
# If HF_DATASET_REPO is set, pulls the dataset from the Hub.
# Otherwise expects {zip} next to the notebook.
import os, zipfile

HF_DATASET_REPO = os.environ.get("HF_DATASET_REPO", "").strip()

if os.path.isdir("dataset"):
    print("[annotix] dataset/ already present — skipping bootstrap")
elif HF_DATASET_REPO:
    from huggingface_hub import snapshot_download
    print(f"[annotix] downloading dataset from {{HF_DATASET_REPO}}")
    local = snapshot_download(repo_id=HF_DATASET_REPO, repo_type="dataset", local_dir="dataset")
    print(f"[annotix] dataset at {{local}}")
elif os.path.exists("{zip}"):
    with zipfile.ZipFile("{zip}") as z:
        z.extractall(".")
    print(f"[annotix] extracted {zip}")
else:
    raise FileNotFoundError(
        "No dataset/, no HF_DATASET_REPO, and no {zip} next to the notebook."
    )
"#),
        Platform::Generic => format!(
r#"# Annotix bootstrap — local / generic
import os, zipfile
from pathlib import Path

HERE = Path.cwd()
ZIP = HERE / "{zip}"

if (HERE / "dataset").is_dir():
    print("[annotix] dataset/ already present — skipping bootstrap")
elif ZIP.exists():
    with zipfile.ZipFile(ZIP) as z:
        z.extractall(HERE)
    print(f"[annotix] extracted {{ZIP.name}}")
else:
    raise FileNotFoundError(
        f"Neither dataset/ nor {{ZIP.name}} exists in {{HERE}}. "
        "Place the zip next to the notebook or extract it beforehand."
    )

# Minimal validation
required = [HERE / "dataset" / "data.yaml"]
missing = [p for p in required if not p.exists()]
if missing:
    print(f"[annotix] warning: missing paths {{missing}} — check the package")
"#),
    }
}

const HF_AUTH_CELL: &str = r#"# HuggingFace auth (token from HF_TOKEN env var or interactive login)
import os
try:
    from huggingface_hub import login, HfApi
    token = os.environ.get("HF_TOKEN")
    if token:
        login(token=token, add_to_git_credential=False)
        print("[annotix] HF login OK (env)")
    else:
        login()  # prompts for token
except Exception as e:
    print(f"[annotix] HF login skipped: {e}")
"#;

fn next_steps_md(platform: Platform) -> &'static str {
    match platform {
        Platform::Colab =>
"Artifacts land in `dataset/train/` (weights, metrics, curves). \
Run the next cell to bundle and download them.",
        Platform::Kaggle =>
"Artifacts land in `/kaggle/working/`. When the session ends they show up in the notebook's *Output* panel.",
        Platform::HuggingFace =>
"Artifacts land in `dataset/train/`. The next cell can push them to the Hub if you set `HF_MODEL_REPO`.",
        Platform::Generic =>
"Artifacts land in `dataset/train/` next to the notebook.",
    }
}

fn results_cell(platform: Platform) -> String {
    match platform {
        Platform::Colab => r#"# Bundle and download the results
import os, shutil, glob
from google.colab import files  # type: ignore

run_dirs = sorted(glob.glob("dataset/**/weights", recursive=True))
out_root = os.path.dirname(run_dirs[0]) if run_dirs else "dataset"
zip_path = shutil.make_archive("annotix_results", "zip", out_root)
print(f"[annotix] zip: {zip_path} ({os.path.getsize(zip_path)/1e6:.1f} MB)")
files.download(zip_path)
"#.to_string(),
        Platform::Kaggle => r#"# Bundle results under /kaggle/working/ (exposed in the Output panel)
import os, shutil, glob
run_dirs = sorted(glob.glob("/kaggle/working/dataset/**/weights", recursive=True))
out_root = os.path.dirname(run_dirs[0]) if run_dirs else "/kaggle/working/dataset"
zip_path = shutil.make_archive("/kaggle/working/annotix_results", "zip", out_root)
print(f"[annotix] zip: {zip_path} ({os.path.getsize(zip_path)/1e6:.1f} MB)")
print("Download it from the 'Output' panel when the session ends.")
"#.to_string(),
        Platform::HuggingFace => r##"# Optional: push the weights to the Hub
import os, glob
HF_MODEL_REPO = os.environ.get("HF_MODEL_REPO", "").strip()
if not HF_MODEL_REPO:
    print("[annotix] HF_MODEL_REPO not set — skipping upload. "
          "To upload, export HF_MODEL_REPO=<user>/<repo> and re-run this cell.")
else:
    from huggingface_hub import HfApi, create_repo
    api = HfApi()
    create_repo(HF_MODEL_REPO, repo_type="model", exist_ok=True)
    run_dirs = sorted(glob.glob("dataset/**/weights", recursive=True))
    folder = os.path.dirname(run_dirs[0]) if run_dirs else "dataset"
    card = f"# {HF_MODEL_REPO}\n\nModel trained with Annotix.\n"
    with open(os.path.join(folder, "README.md"), "w") as f:
        f.write(card)
    api.upload_folder(folder_path=folder, repo_id=HF_MODEL_REPO, repo_type="model")
    print(f"[annotix] uploaded to https://huggingface.co/{HF_MODEL_REPO}")
"##.to_string(),
        Platform::Generic => r#"# Local artifact summary
import glob, os
for p in sorted(glob.glob("dataset/**/weights/*", recursive=True)):
    print(f"{p}  ({os.path.getsize(p)/1e6:.1f} MB)")
"#.to_string(),
    }
}

/// Genera la celda de auto-tune: detecta GPU/CPU, elige batch/workers/amp
/// según VRAM y, para backends basados en ultralytics (YOLO / RT-DETR),
/// parchea `YOLO.train` / `RTDETR.train` para inyectar los overrides sin
/// tener que editar el `train.py` generado.
fn build_autotune_cell(backend: &str) -> String {
    let patch_block = match backend {
        "YOLO" | "RT-DETR" => r#"
# Monkey-patch ultralytics para aplicar overrides sin tocar train.py
try:
    from ultralytics import YOLO as _AnnotixYOLO
    _orig_yolo_train = _AnnotixYOLO.train
    def _annotix_yolo_train(self, **kwargs):
        kwargs["device"]  = os.environ["ANNOTIX_DEVICE"]
        kwargs["batch"]   = int(os.environ["ANNOTIX_BATCH"])
        kwargs["workers"] = int(os.environ["ANNOTIX_WORKERS"])
        kwargs["amp"]     = os.environ["ANNOTIX_AMP"] == "1"
        print(f"[annotix] YOLO.train overrides → device={kwargs['device']} "
              f"batch={kwargs['batch']} workers={kwargs['workers']} amp={kwargs['amp']}")
        return _orig_yolo_train(self, **kwargs)
    _AnnotixYOLO.train = _annotix_yolo_train
except Exception as _e:
    print(f"[annotix] YOLO patch skipped: {_e}")

try:
    from ultralytics import RTDETR as _AnnotixRTDETR
    _orig_rtdetr_train = _AnnotixRTDETR.train
    def _annotix_rtdetr_train(self, **kwargs):
        kwargs["device"]  = os.environ["ANNOTIX_DEVICE"]
        kwargs["batch"]   = int(os.environ["ANNOTIX_BATCH"])
        kwargs["workers"] = int(os.environ["ANNOTIX_WORKERS"])
        kwargs["amp"]     = os.environ["ANNOTIX_AMP"] == "1"
        return _orig_rtdetr_train(self, **kwargs)
    _AnnotixRTDETR.train = _annotix_rtdetr_train
except Exception:
    pass
"#,
        _ => r#"
# For this backend overrides are exposed via env vars
# (ANNOTIX_DEVICE / ANNOTIX_BATCH / ANNOTIX_WORKERS / ANNOTIX_AMP).
"#,
    };

    format!(
r#"# Annotix · hardware auto-tune
import os, multiprocessing

try:
    import torch
    _has_cuda = torch.cuda.is_available()
    _has_mps = getattr(torch.backends, "mps", None) and torch.backends.mps.is_available()
except Exception:
    torch = None
    _has_cuda = False
    _has_mps = False

if _has_cuda:
    _name = torch.cuda.get_device_name(0)
    _props = torch.cuda.get_device_properties(0)
    _vram_gb = _props.total_memory / (1024 ** 3)
    _cc = f"{{_props.major}}.{{_props.minor}}"
    print(f"[annotix] GPU: {{_name}} · {{_vram_gb:.1f}} GB · CC {{_cc}}")

    if _vram_gb >= 70:       # H100 80, A100 80
        _batch = 96
    elif _vram_gb >= 38:     # A100 40
        _batch = 64
    elif _vram_gb >= 22:     # L4 24, 3090, 4090
        _batch = 32
    elif _vram_gb >= 14:     # T4 16, V100 16, P100 16
        _batch = 16
    elif _vram_gb >= 10:
        _batch = 12
    else:
        _batch = 8

    _device = "0"
    _workers = 4
    _amp = _props.major >= 7
elif _has_mps:
    print("[annotix] Apple Silicon MPS detected")
    _device = "mps"
    _batch = 8
    _workers = 2
    _amp = False
else:
    print("[annotix] no GPU — falling back to CPU (training will be slow)")
    _device = "cpu"
    _batch = 8
    _workers = max(2, multiprocessing.cpu_count() // 2)
    _amp = False

os.environ["ANNOTIX_DEVICE"]  = os.environ.get("ANNOTIX_DEVICE",  _device)
os.environ["ANNOTIX_BATCH"]   = os.environ.get("ANNOTIX_BATCH",   str(_batch))
os.environ["ANNOTIX_WORKERS"] = os.environ.get("ANNOTIX_WORKERS", str(_workers))
os.environ["ANNOTIX_AMP"]     = os.environ.get("ANNOTIX_AMP",     "1" if _amp else "0")

print(f"[annotix] tuned → device={{os.environ['ANNOTIX_DEVICE']}} "
      f"batch={{os.environ['ANNOTIX_BATCH']}} "
      f"workers={{os.environ['ANNOTIX_WORKERS']}} "
      f"amp={{os.environ['ANNOTIX_AMP']}}")
{patch_block}"#,
        patch_block = patch_block,
    )
}

fn md_lines(s: &str) -> Vec<String> {
    s.lines().map(|l| format!("{}\n", l)).collect()
}

fn code_lines(s: &str) -> Vec<String> {
    s.lines().map(|l| format!("{}\n", l)).collect()
}

fn split_script_blocks(script: &str) -> Vec<String> {
    let mut blocks = Vec::new();
    let mut current = String::new();

    for line in script.lines() {
        if (line.starts_with("def ") || line.starts_with("class ") || line.starts_with("if __name__"))
            && !current.trim().is_empty()
        {
            blocks.push(current.trim().to_string());
            current = String::new();
        }
        if line.starts_with("#!") {
            continue;
        }
        current.push_str(line);
        current.push('\n');
    }

    if !current.trim().is_empty() {
        let trimmed = current.trim();
        if !trimmed.contains("if __name__") {
            blocks.push(trimmed.to_string());
        }
    }

    if blocks.is_empty() {
        blocks.push(script.to_string());
    }

    blocks
}
