use std::io::Write;
use std::path::Path;

use crate::store::project_file::{ProjectFile, ImageEntry};
use super::{TrainingRequest, TrainingBackend};
use super::dataset;
use super::scripts;
use super::notebook;

/// Generates a ZIP training package at output_path
pub fn generate_training_package(
    images_dir: &Path,
    project: &ProjectFile,
    images: &[ImageEntry],
    request: &TrainingRequest,
    output_path: &str,
) -> Result<String, String> {
    let temp_dir = tempfile::tempdir()
        .map_err(|e| format!("Error creando directorio temporal: {}", e))?;
    let pkg_dir = temp_dir.path().join("package");
    let dataset_dir = pkg_dir.join("dataset");
    std::fs::create_dir_all(&dataset_dir)
        .map_err(|e| format!("Error creando dataset dir: {}", e))?;

    // 1. Prepare dataset
    let dataset_path = dataset::prepare_dataset_for_backend(
        images_dir, project, images, &dataset_dir,
        request.val_split, &request.task, &request.backend,
    )?;

    // 2. Generate scripts
    let num_classes = project.classes.len();
    let script_files = scripts::generate_train_script_for_backend(request, &dataset_path, num_classes);

    for (filename, content) in &script_files {
        let path = pkg_dir.join(filename);
        std::fs::write(&path, content)
            .map_err(|e| format!("Error escribiendo {}: {}", filename, e))?;
    }

    // 3. Generate requirements.txt
    let requirements = scripts::get_requirements_for_backend(&request.backend);
    let req_content = requirements.join("\n") + "\n";
    std::fs::write(pkg_dir.join("requirements.txt"), &req_content)
        .map_err(|e| format!("Error escribiendo requirements.txt: {}", e))?;

    // 4. Generate notebook
    let train_script = script_files.iter()
        .find(|(name, _)| name == "train.py")
        .map(|(_, content)| content.as_str())
        .unwrap_or("");

    let backend_name = match request.backend {
        TrainingBackend::Yolo => "YOLO",
        TrainingBackend::RtDetr => "RT-DETR",
        TrainingBackend::RfDetr => "RF-DETR",
        TrainingBackend::MmDetection => "MMDetection",
    };

    let nb_content = notebook::script_to_notebook(
        &format!("{} Training — {}", backend_name, request.model_id),
        &format!("Training package for {} model {} on task: {}", backend_name, request.model_id, request.task),
        &requirements,
        train_script,
    );
    std::fs::write(pkg_dir.join("train.ipynb"), &nb_content)
        .map_err(|e| format!("Error escribiendo train.ipynb: {}", e))?;

    // 5. Generate README
    let readme = generate_readme(backend_name, &request.model_id, &request.task, &requirements);
    std::fs::write(pkg_dir.join("README.md"), &readme)
        .map_err(|e| format!("Error escribiendo README.md: {}", e))?;

    // 6. Create ZIP
    let zip_path = Path::new(output_path);
    let zip_file = std::fs::File::create(zip_path)
        .map_err(|e| format!("Error creando ZIP: {}", e))?;
    let mut zip_writer = zip::ZipWriter::new(zip_file);
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated);

    add_dir_to_zip(&mut zip_writer, &pkg_dir, &pkg_dir, options)?;

    zip_writer.finish()
        .map_err(|e| format!("Error finalizando ZIP: {}", e))?;

    Ok(output_path.to_string())
}

fn add_dir_to_zip(
    zip: &mut zip::ZipWriter<std::fs::File>,
    base: &Path,
    dir: &Path,
    options: zip::write::SimpleFileOptions,
) -> Result<(), String> {
    for entry in std::fs::read_dir(dir).map_err(|e| e.to_string())? {
        let entry = entry.map_err(|e| e.to_string())?;
        let path = entry.path();
        let relative = path.strip_prefix(base).map_err(|e| e.to_string())?;
        let name = relative.to_string_lossy().replace('\\', "/");

        if path.is_dir() {
            zip.add_directory(&format!("{}/", name), options)
                .map_err(|e| format!("Error adding dir to zip: {}", e))?;
            add_dir_to_zip(zip, base, &path, options)?;
        } else {
            zip.start_file(&name, options)
                .map_err(|e| format!("Error adding file to zip: {}", e))?;
            let data = std::fs::read(&path)
                .map_err(|e| format!("Error reading file {}: {}", name, e))?;
            zip.write_all(&data)
                .map_err(|e| format!("Error writing file to zip: {}", e))?;
        }
    }
    Ok(())
}

fn generate_readme(backend: &str, model_id: &str, task: &str, requirements: &[&str]) -> String {
    format!(
r#"# Training Package — {backend}

**Model:** {model_id}
**Task:** {task}
**Generated by:** Annotix

## Contents

- `dataset/` — Prepared training dataset
- `train.py` — Training script
- `train.ipynb` — Jupyter notebook (equivalent)
- `requirements.txt` — Python dependencies

## Quick Start

```bash
# 1. Install dependencies
pip install -r requirements.txt

# 2. Run training
python train.py
```

## Using the Notebook

```bash
jupyter notebook train.ipynb
```

## Requirements

{req_list}
"#,
        backend = backend,
        model_id = model_id,
        task = task,
        req_list = requirements.iter().map(|r| format!("- {}", r)).collect::<Vec<_>>().join("\n"),
    )
}
