use super::TrainingConfig;

/// Genera el script train.py que se ejecutará en el virtualenv
pub fn generate_train_script(config: &TrainingConfig, data_yaml_path: &str) -> String {
    let model_name = build_model_name(config);
    let task_suffix = task_arg(&config.task);
    let data_yaml_path_quoted = format!("r\"{}\"", data_yaml_path.replace('\\', "\\\\"));
    let device_quoted = format_device(&config.device);
    let task_line = if !task_suffix.is_empty() {
        format!("train_args[\"task\"] = \"{}\"", config.task)
    } else {
        "# Default detection task".to_string()
    };
    let export_section = generate_export_section(&config.export_formats);

    format!(
        r#"#!/usr/bin/env python3
"""
YOLO Training Script - Generated by Annotix
Model: {model_name}
"""
import sys
import json
import os

def main():
    from ultralytics import YOLO

    data_yaml = {data_yaml_path_quoted}

    # Load model
    model = YOLO("{model_name}")

    # Training config
    train_args = {{
        "data": data_yaml,
        "epochs": {epochs},
        "batch": {batch},
        "imgsz": {imgsz},
        "device": {device_quoted},
        "optimizer": "{optimizer}",
        "lr0": {lr0},
        "lrf": {lrf},
        "patience": {patience},
        "workers": {workers},
        "project": os.path.dirname(data_yaml),
        "name": "train",
        "exist_ok": True,
        "verbose": True,
        # Augmentation
        "mosaic": {mosaic},
        "mixup": {mixup},
        "hsv_h": {hsv_h},
        "hsv_s": {hsv_s},
        "hsv_v": {hsv_v},
        "flipud": {flipud},
        "fliplr": {fliplr},
        "degrees": {degrees},
        "scale": {scale},
        "shear": {shear},
        "perspective": {perspective},
        "copy_paste": {copy_paste},
        "erasing": {erasing},
    }}

    {task_line}

    # Register callback for epoch metrics
    def on_fit_epoch_end(trainer):
        metrics = {{}}
        epoch = trainer.epoch + 1
        total = trainer.epochs

        # Gather available metrics
        if hasattr(trainer, 'metrics'):
            m = trainer.metrics
            if isinstance(m, dict):
                metrics["precision"] = m.get("metrics/precision(B)", None)
                metrics["recall"] = m.get("metrics/recall(B)", None)
                metrics["mAP50"] = m.get("metrics/mAP50(B)", None)
                metrics["mAP50_95"] = m.get("metrics/mAP50-95(B)", None)

        if hasattr(trainer, 'loss_items') and trainer.loss_items is not None:
            try:
                loss_items = trainer.loss_items.cpu().numpy()
                if len(loss_items) >= 3:
                    metrics["boxLoss"] = float(loss_items[0])
                    metrics["clsLoss"] = float(loss_items[1])
                    metrics["dflLoss"] = float(loss_items[2])
            except Exception:
                pass

        if hasattr(trainer, 'tloss') and trainer.tloss is not None:
            try:
                metrics["trainLoss"] = float(trainer.tloss.cpu().numpy())
            except Exception:
                pass

        if hasattr(trainer, 'lr') and trainer.lr:
            try:
                metrics["lr"] = list(trainer.lr.values())[0] if isinstance(trainer.lr, dict) else float(trainer.lr)
            except Exception:
                pass

        progress = (epoch / total) * 100.0

        event = {{
            "type": "epoch",
            "epoch": epoch,
            "totalEpochs": total,
            "progress": progress,
            "metrics": metrics,
        }}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    model.add_callback("on_fit_epoch_end", on_fit_epoch_end)

    # Start training
    results = model.train(**train_args)

    # Collect results
    train_dir = os.path.join(os.path.dirname(data_yaml), "train")
    best_model = os.path.join(train_dir, "weights", "best.pt")
    last_model = os.path.join(train_dir, "weights", "last.pt")

    result = {{
        "type": "completed",
        "bestModelPath": best_model if os.path.exists(best_model) else None,
        "lastModelPath": last_model if os.path.exists(last_model) else None,
        "resultsDir": train_dir,
    }}

    # Final metrics
    if results and hasattr(results, 'results_dict'):
        rd = results.results_dict
        result["finalMetrics"] = {{
            "precision": rd.get("metrics/precision(B)", None),
            "recall": rd.get("metrics/recall(B)", None),
            "mAP50": rd.get("metrics/mAP50(B)", None),
            "mAP50_95": rd.get("metrics/mAP50-95(B)", None),
        }}

    {export_section}

    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        model_name = model_name,
        data_yaml_path_quoted = data_yaml_path_quoted,
        epochs = config.epochs,
        batch = config.batch_size,
        imgsz = config.imgsz,
        device_quoted = device_quoted,
        optimizer = config.optimizer,
        lr0 = config.lr0,
        lrf = config.lrf,
        patience = config.patience,
        workers = config.workers,
        mosaic = config.augmentation.mosaic,
        mixup = config.augmentation.mixup,
        hsv_h = config.augmentation.hsv_h,
        hsv_s = config.augmentation.hsv_s,
        hsv_v = config.augmentation.hsv_v,
        flipud = config.augmentation.flipud,
        fliplr = config.augmentation.fliplr,
        degrees = config.augmentation.degrees,
        scale = config.augmentation.scale,
        shear = config.augmentation.shear,
        perspective = config.augmentation.perspective,
        copy_paste = config.augmentation.copy_paste,
        erasing = config.augmentation.erasing,
        task_line = task_line,
        export_section = export_section,
    )
}

/// Genera el script para exportar un modelo entrenado
pub fn generate_export_script(model_path: &str, format: &str) -> String {
    format!(
        r#"
from ultralytics import YOLO
import json

model = YOLO(r"{model_path}")
path = model.export(format="{format}")
result = {{"type": "export_done", "format": "{format}", "path": str(path)}}
print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)
"#,
        model_path = model_path,
        format = format,
    )
}

fn build_model_name(config: &TrainingConfig) -> String {
    let version = config.yolo_version.to_lowercase();
    let size = &config.model_size;
    let task = &config.task;

    let task_suffix = match task.as_str() {
        "segment" => "-seg",
        "classify" => "-cls",
        "pose" => "-pose",
        "obb" => "-obb",
        _ => "", // detect = no suffix
    };

    // Mapear versión a nombre de modelo ultralytics
    match version.as_str() {
        "yolo26" => format!("yolo26{}{}.pt", size, task_suffix),
        "yolo12" => format!("yolo12{}{}.pt", size, task_suffix),
        "yolo11" => format!("yolo11{}{}.pt", size, task_suffix),
        "yolov10" => format!("yolov10{}.pt", size), // v10 solo detect
        "yolov9" => format!("yolov9{}{}.pt", size, task_suffix),
        "yolov8" => format!("yolov8{}{}.pt", size, task_suffix),
        "yolov5" | "yolov5u" => format!("yolov5{}u{}.pt", size, task_suffix),
        _ => format!("yolo11{}{}.pt", size, task_suffix), // fallback
    }
}

fn task_arg(task: &str) -> &str {
    match task {
        "detect" => "",
        "segment" => "segment",
        "classify" => "classify",
        "pose" => "pose",
        "obb" => "obb",
        _ => "",
    }
}

fn format_device(device: &str) -> String {
    match device {
        "auto" => "\"\"".to_string(), // ultralytics auto-detect
        "cpu" => "\"cpu\"".to_string(),
        "mps" => "\"mps\"".to_string(),
        d if d.starts_with("cuda") => format!("\"{}\"", d),
        d => format!("\"{}\"", d),
    }
}

fn generate_export_section(formats: &[String]) -> String {
    if formats.is_empty() {
        return "# No export formats requested".to_string();
    }

    let mut lines = vec![
        "    # Export model to requested formats".to_string(),
        "    exported = []".to_string(),
        format!("    best = YOLO(best_model) if os.path.exists(best_model) else model"),
    ];

    for fmt in formats {
        lines.push(format!(
            "    try:\n        export_path = best.export(format=\"{fmt}\")\n        exported.append({{\"format\": \"{fmt}\", \"path\": str(export_path)}})\n    except Exception as e:\n        print(f\"Warning: export to {fmt} failed: {{e}}\", file=sys.stderr)",
            fmt = fmt,
        ));
    }

    lines.push("    result[\"exportedModels\"] = exported".to_string());
    lines.join("\n")
}
