use super::{TrainingConfig, TrainingRequest, TrainingBackend};

fn py_bool(val: bool) -> &'static str {
    if val { "True" } else { "False" }
}

/// Genera el script train.py que se ejecutará en el virtualenv
pub fn generate_train_script(config: &TrainingConfig, data_yaml_path: &str) -> String {
    let model_name = build_model_name(config);
    let task_suffix = task_arg(&config.task);
    let data_yaml_path_quoted = format!("r\"{}\"", data_yaml_path.replace('\\', "/"));
    let device_quoted = format_device(&config.device);
    let task_line = if !task_suffix.is_empty() {
        format!("train_args[\"task\"] = \"{}\"", config.task)
    } else {
        "# Default detection task".to_string()
    };
    let export_section = generate_export_section(&config.export_formats);

    let cache_value = config.cache.to_python();

    let freeze_line = match config.freeze {
        Some(n) if n > 0 => format!("        \"freeze\": {},", n),
        _ => "        # freeze: disabled".to_string(),
    };

    format!(
        r#"#!/usr/bin/env python3
"""
YOLO Training Script - Generated by Annotix
Model: {model_name}
"""
import sys
import json
import os

def main():
    from ultralytics import YOLO

    data_yaml = {data_yaml_path_quoted}

    # Load model
    model = YOLO("{model_name}")

    # Training config
    train_args = {{
        "data": data_yaml,
        "epochs": {epochs},
        "batch": {batch},
        "imgsz": {imgsz},
        "device": {device_quoted},
        "optimizer": "{optimizer}",
        "lr0": {lr0},
        "lrf": {lrf},
        "patience": {patience},
        "workers": {workers},
        "project": os.path.dirname(data_yaml),
        "name": "train",
        "exist_ok": True,
        "verbose": True,
        # Optimizer
        "cos_lr": {cos_lr},
        "warmup_epochs": {warmup_epochs},
        "warmup_momentum": {warmup_momentum},
        "warmup_bias_lr": {warmup_bias_lr},
        "momentum": {momentum},
        "weight_decay": {weight_decay},
        "nbs": {nbs},
        # Loss weights
        "box": {box_weight},
        "cls": {cls_weight},
        "dfl": {dfl_weight},
        # Advanced
        "close_mosaic": {close_mosaic},
        "max_det": {max_det},
        "multi_scale": {multi_scale},
        "rect": {rect},
        "cache": {cache_value},
        "amp": {amp},
        "single_cls": {single_cls},
        "pretrained": {pretrained},
{freeze_line}
        # Augmentation
        "mosaic": {mosaic},
        "mixup": {mixup},
        "hsv_h": {hsv_h},
        "hsv_s": {hsv_s},
        "hsv_v": {hsv_v},
        "flipud": {flipud},
        "fliplr": {fliplr},
        "degrees": {degrees},
        "scale": {scale},
        "shear": {shear},
        "perspective": {perspective},
        "copy_paste": {copy_paste},
        "erasing": {erasing},
        "translate": {translate},
    }}

    {task_line}

    # Register callback for epoch metrics
    def on_fit_epoch_end(trainer):
        metrics = {{}}
        epoch = trainer.epoch + 1
        total = trainer.epochs

        # Gather available metrics
        if hasattr(trainer, 'metrics'):
            m = trainer.metrics
            if isinstance(m, dict):
                metrics["precision"] = m.get("metrics/precision(B)", None)
                metrics["recall"] = m.get("metrics/recall(B)", None)
                metrics["mAP50"] = m.get("metrics/mAP50(B)", None)
                metrics["mAP50_95"] = m.get("metrics/mAP50-95(B)", None)

        if hasattr(trainer, 'loss_items') and trainer.loss_items is not None:
            try:
                loss_items = trainer.loss_items.cpu().numpy()
                if len(loss_items) >= 3:
                    metrics["boxLoss"] = float(loss_items[0])
                    metrics["clsLoss"] = float(loss_items[1])
                    metrics["dflLoss"] = float(loss_items[2])
            except Exception:
                pass

        if hasattr(trainer, 'tloss') and trainer.tloss is not None:
            try:
                metrics["trainLoss"] = float(trainer.tloss.cpu().numpy())
            except Exception:
                pass

        if hasattr(trainer, 'lr') and trainer.lr:
            try:
                metrics["lr"] = list(trainer.lr.values())[0] if isinstance(trainer.lr, dict) else float(trainer.lr)
            except Exception:
                pass

        progress = (epoch / total) * 100.0

        event = {{
            "type": "epoch",
            "epoch": epoch,
            "totalEpochs": total,
            "progress": progress,
            "metrics": metrics,
        }}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    model.add_callback("on_fit_epoch_end", on_fit_epoch_end)

    # Start training
    results = model.train(**train_args)

    # Collect results
    train_dir = os.path.join(os.path.dirname(data_yaml), "train")
    best_model = os.path.join(train_dir, "weights", "best.pt")
    last_model = os.path.join(train_dir, "weights", "last.pt")

    result = {{
        "type": "completed",
        "bestModelPath": best_model if os.path.exists(best_model) else None,
        "lastModelPath": last_model if os.path.exists(last_model) else None,
        "resultsDir": train_dir,
    }}

    # Final metrics
    if results and hasattr(results, 'results_dict'):
        rd = results.results_dict
        result["finalMetrics"] = {{
            "precision": rd.get("metrics/precision(B)", None),
            "recall": rd.get("metrics/recall(B)", None),
            "mAP50": rd.get("metrics/mAP50(B)", None),
            "mAP50_95": rd.get("metrics/mAP50-95(B)", None),
        }}

    {export_section}

    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        model_name = model_name,
        data_yaml_path_quoted = data_yaml_path_quoted,
        epochs = config.epochs,
        batch = config.batch_size,
        imgsz = config.imgsz,
        device_quoted = device_quoted,
        optimizer = config.optimizer,
        lr0 = config.lr0,
        lrf = config.lrf,
        patience = config.patience,
        workers = config.workers,
        // Optimizer
        cos_lr = py_bool(config.cos_lr),
        warmup_epochs = config.warmup_epochs,
        warmup_momentum = config.warmup_momentum,
        warmup_bias_lr = config.warmup_bias_lr,
        momentum = config.momentum,
        weight_decay = config.weight_decay,
        nbs = config.nbs,
        // Loss weights
        box_weight = config.box_weight,
        cls_weight = config.cls,
        dfl_weight = config.dfl,
        // Advanced
        close_mosaic = config.close_mosaic,
        max_det = config.max_det,
        multi_scale = config.multi_scale,
        rect = py_bool(config.rect),
        cache_value = cache_value,
        amp = py_bool(config.amp),
        single_cls = py_bool(config.single_cls),
        pretrained = py_bool(config.pretrained),
        freeze_line = freeze_line,
        // Augmentation
        mosaic = config.augmentation.mosaic,
        mixup = config.augmentation.mixup,
        hsv_h = config.augmentation.hsv_h,
        hsv_s = config.augmentation.hsv_s,
        hsv_v = config.augmentation.hsv_v,
        flipud = config.augmentation.flipud,
        fliplr = config.augmentation.fliplr,
        degrees = config.augmentation.degrees,
        scale = config.augmentation.scale,
        shear = config.augmentation.shear,
        perspective = config.augmentation.perspective,
        copy_paste = config.augmentation.copy_paste,
        erasing = config.augmentation.erasing,
        translate = config.augmentation.translate,
        task_line = task_line,
        export_section = export_section,
    )
}

/// Genera el script para exportar un modelo entrenado
pub fn generate_export_script(model_path: &str, format: &str) -> String {
    format!(
        r#"
from ultralytics import YOLO
import json

model = YOLO(r"{model_path}")
path = model.export(format="{format}")
result = {{"type": "export_done", "format": "{format}", "path": str(path)}}
print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)
"#,
        model_path = model_path,
        format = format,
    )
}

fn build_model_name(config: &TrainingConfig) -> String {
    // Si hay un path a modelo base (fine-tune), usarlo directamente
    if let Some(ref path) = config.base_model_path {
        if !path.is_empty() {
            return path.replace('\\', "/");
        }
    }

    let version = config.yolo_version.to_lowercase();
    let size = &config.model_size;
    let task = &config.task;

    let task_suffix = match task.as_str() {
        "segment" => "-seg",
        "classify" => "-cls",
        "pose" => "-pose",
        "obb" => "-obb",
        _ => "", // detect = no suffix
    };

    // Mapear versión a nombre de modelo ultralytics
    match version.as_str() {
        "yolo26" => format!("yolo26{}{}.pt", size, task_suffix),
        "yolo12" => format!("yolo12{}{}.pt", size, task_suffix),
        "yolo11" => format!("yolo11{}{}.pt", size, task_suffix),
        "yolov10" => format!("yolov10{}.pt", size), // v10 solo detect
        "yolov9" => format!("yolov9{}{}.pt", size, task_suffix),
        "yolov8" => format!("yolov8{}{}.pt", size, task_suffix),
        "yolov5" | "yolov5u" => format!("yolov5{}u{}.pt", size, task_suffix),
        _ => format!("yolo11{}{}.pt", size, task_suffix), // fallback
    }
}

fn task_arg(task: &str) -> &str {
    match task {
        "detect" => "",
        "segment" => "segment",
        "classify" => "classify",
        "pose" => "pose",
        "obb" => "obb",
        _ => "",
    }
}

fn format_device(device: &str) -> String {
    match device {
        "auto" => "\"\"".to_string(), // ultralytics auto-detect
        "cpu" => "\"cpu\"".to_string(),
        "mps" => "\"mps\"".to_string(),
        d if d.starts_with("cuda") => format!("\"{}\"", d),
        d => format!("\"{}\"", d),
    }
}

// ─── RT-DETR Script ──────────────────────────────────────────────────────────

pub fn generate_rtdetr_script(req: &TrainingRequest, data_yaml_path: &str) -> String {
    let bp = &req.backend_params;
    let model_name = match &req.base_model_path {
        Some(path) if !path.is_empty() => path.replace('\\', "/"),
        _ => format!("{}.pt", req.model_id),
    };
    let device = format_device(&req.device);
    let lrf = bp.get("lrf").and_then(|v| v.as_f64()).unwrap_or(0.01);
    let optimizer = bp.get("optimizer").and_then(|v| v.as_str()).unwrap_or("AdamW");
    let warmup_epochs = bp.get("warmup_epochs").and_then(|v| v.as_f64()).unwrap_or(3.0);
    let weight_decay = bp.get("weight_decay").and_then(|v| v.as_f64()).unwrap_or(0.0001);
    let freeze_line = match bp.get("freeze").and_then(|v| v.as_u64()) {
        Some(n) if n > 0 => format!("        \"freeze\": {},", n),
        _ => "        # freeze: disabled".to_string(),
    };

    format!(
        r#"#!/usr/bin/env python3
"""
RT-DETR Training Script - Generated by Annotix
Model: {model_name}
"""
import sys
import json
import os

def main():
    from ultralytics import RTDETR

    data_yaml = r"{data_yaml}"

    model = RTDETR("{model_name}")

    train_args = {{
        "data": data_yaml,
        "epochs": {epochs},
        "batch": {batch},
        "imgsz": {imgsz},
        "device": {device},
        "optimizer": "{optimizer}",
        "lr0": {lr},
        "lrf": {lrf},
        "patience": {patience},
        "workers": {workers},
        "project": os.path.dirname(data_yaml),
        "name": "train",
        "exist_ok": True,
        "verbose": True,
        "warmup_epochs": {warmup_epochs},
        "weight_decay": {weight_decay},
        "amp": {amp},
{freeze_line}
    }}

    def on_fit_epoch_end(trainer):
        metrics = {{}}
        epoch = trainer.epoch + 1
        total = trainer.epochs

        if hasattr(trainer, 'metrics'):
            m = trainer.metrics
            if isinstance(m, dict):
                metrics["precision"] = m.get("metrics/precision(B)", None)
                metrics["recall"] = m.get("metrics/recall(B)", None)
                metrics["mAP50"] = m.get("metrics/mAP50(B)", None)
                metrics["mAP50_95"] = m.get("metrics/mAP50-95(B)", None)

        if hasattr(trainer, 'tloss') and trainer.tloss is not None:
            try:
                metrics["trainLoss"] = float(trainer.tloss.cpu().numpy())
            except Exception:
                pass

        if hasattr(trainer, 'lr') and trainer.lr:
            try:
                metrics["lr"] = list(trainer.lr.values())[0] if isinstance(trainer.lr, dict) else float(trainer.lr)
            except Exception:
                pass

        progress = (epoch / total) * 100.0
        event = {{
            "type": "epoch",
            "epoch": epoch,
            "totalEpochs": total,
            "progress": progress,
            "metrics": metrics,
        }}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    model.add_callback("on_fit_epoch_end", on_fit_epoch_end)

    results = model.train(**train_args)

    train_dir = os.path.join(os.path.dirname(data_yaml), "train")
    best_model = os.path.join(train_dir, "weights", "best.pt")
    last_model = os.path.join(train_dir, "weights", "last.pt")

    result = {{
        "type": "completed",
        "bestModelPath": best_model if os.path.exists(best_model) else None,
        "lastModelPath": last_model if os.path.exists(last_model) else None,
        "resultsDir": train_dir,
    }}

    if results and hasattr(results, 'results_dict'):
        rd = results.results_dict
        result["finalMetrics"] = {{
            "precision": rd.get("metrics/precision(B)", None),
            "recall": rd.get("metrics/recall(B)", None),
            "mAP50": rd.get("metrics/mAP50(B)", None),
            "mAP50_95": rd.get("metrics/mAP50-95(B)", None),
        }}

    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        model_name = model_name,
        data_yaml = data_yaml_path.replace('\\', "/"),
        epochs = req.epochs,
        batch = req.batch_size,
        imgsz = req.image_size,
        device = device,
        optimizer = optimizer,
        lr = req.lr,
        lrf = lrf,
        patience = req.patience,
        workers = req.workers,
        warmup_epochs = warmup_epochs,
        weight_decay = weight_decay,
        amp = py_bool(req.amp),
        freeze_line = freeze_line,
    )
}

// ─── RF-DETR Script ──────────────────────────────────────────────────────────

pub fn generate_rfdetr_script(req: &TrainingRequest, dataset_dir: &str) -> String {
    let bp = &req.backend_params;
    let model_class = &req.model_id; // e.g. "RFDETRBase"
    let resolution = bp.get("resolution").and_then(|v| v.as_u64()).unwrap_or(560);
    let lr_encoder = bp.get("lr_encoder").and_then(|v| v.as_f64()).unwrap_or(1e-5);
    let grad_accum = bp.get("grad_accum_steps").and_then(|v| v.as_u64()).unwrap_or(4);
    let use_ema = bp.get("use_ema").and_then(|v| v.as_bool()).unwrap_or(true);
    let weight_decay = bp.get("weight_decay").and_then(|v| v.as_f64()).unwrap_or(0.0001);
    let gradient_checkpointing = bp.get("gradient_checkpointing").and_then(|v| v.as_bool()).unwrap_or(false);

    format!(
        r#"#!/usr/bin/env python3
"""
RF-DETR Training Script - Generated by Annotix
Model: {model_class}
"""
import sys
import json
import os

def main():
    from rfdetr import {model_class}

    model = {model_class}()

    dataset_dir = r"{dataset_dir}"
    output_dir = os.path.join(dataset_dir, "train_output")
    os.makedirs(output_dir, exist_ok=True)

    # Callback for epoch metrics
    def on_epoch_end(metrics_dict):
        epoch = metrics_dict.get("epoch", 0)
        total = {epochs}
        progress = (epoch / total) * 100.0
        metrics = {{
            "trainLoss": metrics_dict.get("train_loss", None),
            "valLoss": metrics_dict.get("test_loss", None),
        }}
        event = {{
            "type": "epoch",
            "epoch": epoch,
            "totalEpochs": total,
            "progress": progress,
            "metrics": metrics,
        }}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    if hasattr(model, 'callbacks') and "on_fit_epoch_end" in model.callbacks:
        model.callbacks["on_fit_epoch_end"].append(on_epoch_end)

    model.train(
        dataset_dir=dataset_dir,
        epochs={epochs},
        batch_size={batch},
        resolution={resolution},
        lr={lr},
        lr_encoder={lr_encoder},
        grad_accum_steps={grad_accum},
        use_ema={use_ema},
        weight_decay={weight_decay},
        gradient_checkpointing={gradient_checkpointing},
    )

    # Find best checkpoint
    best_model = None
    for name in ["checkpoint_best_total.pth", "checkpoint_best.pth"]:
        candidate = os.path.join(output_dir, name)
        if os.path.exists(candidate):
            best_model = candidate
            break
    if not best_model:
        # Try current dir
        for name in ["checkpoint_best_total.pth", "checkpoint_best.pth"]:
            if os.path.exists(name):
                best_model = os.path.abspath(name)
                break

    result = {{
        "type": "completed",
        "bestModelPath": best_model,
        "lastModelPath": None,
        "resultsDir": output_dir,
    }}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        model_class = model_class,
        dataset_dir = dataset_dir.replace('\\', "/"),
        epochs = req.epochs,
        batch = req.batch_size,
        resolution = resolution,
        lr = req.lr,
        lr_encoder = lr_encoder,
        grad_accum = grad_accum,
        use_ema = py_bool(use_ema),
        weight_decay = weight_decay,
        gradient_checkpointing = py_bool(gradient_checkpointing),
    )
}

// ─── MMDetection Script + Config ─────────────────────────────────────────────

pub fn generate_mmdet_config(req: &TrainingRequest, dataset_dir: &str, num_classes: usize) -> String {
    let bp = &req.backend_params;
    let model_id = &req.model_id;
    let optimizer_type = bp.get("optimizer_type").and_then(|v| v.as_str()).unwrap_or("SGD");
    let momentum = bp.get("momentum").and_then(|v| v.as_f64()).unwrap_or(0.9);
    let weight_decay = bp.get("weight_decay").and_then(|v| v.as_f64()).unwrap_or(0.0001);
    let warmup_iters = bp.get("warmup_iters").and_then(|v| v.as_u64()).unwrap_or(500);
    let checkpoint_interval = bp.get("checkpoint_interval").and_then(|v| v.as_u64()).unwrap_or(1);

    let dataset_dir_escaped = dataset_dir.replace('\\', "/");

    format!(
        r#"# MMDetection Config - Generated by Annotix
_base_ = []

# Model config (auto-downloaded from mmdet registry)
model_name = "{model_id}"

# Dataset
dataset_type = "CocoDataset"
data_root = r"{dataset_dir}"

train_dataloader = dict(
    batch_size={batch},
    num_workers={workers},
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file="annotations/instances_train.json",
        data_prefix=dict(img="train/"),
    ),
)

val_dataloader = dict(
    batch_size=1,
    num_workers={workers},
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        ann_file="annotations/instances_val.json",
        data_prefix=dict(img="val/"),
    ),
)

val_evaluator = dict(
    type="CocoMetric",
    ann_file=data_root + "/annotations/instances_val.json",
    metric="bbox",
)

# Optimizer
optim_wrapper = dict(
    type="OptimWrapper",
    optimizer=dict(type="{optimizer_type}", lr={lr}, momentum={momentum}, weight_decay={weight_decay}),
)

# Schedule
train_cfg = dict(type="EpochBasedTrainLoop", max_epochs={epochs}, val_interval=1)
val_cfg = dict(type="ValLoop")
param_scheduler = [
    dict(type="LinearLR", start_factor=0.001, by_epoch=False, begin=0, end={warmup_iters}),
    dict(type="MultiStepLR", by_epoch=True, milestones=[{epochs_2_3}, {epochs_8_9}], gamma=0.1),
]

# Runtime
default_hooks = dict(
    checkpoint=dict(type="CheckpointHook", interval={checkpoint_interval}),
)

num_classes = {num_classes}
"#,
        model_id = model_id,
        dataset_dir = dataset_dir_escaped,
        batch = req.batch_size,
        workers = req.workers,
        optimizer_type = optimizer_type,
        lr = req.lr,
        momentum = momentum,
        weight_decay = weight_decay,
        epochs = req.epochs,
        warmup_iters = warmup_iters,
        checkpoint_interval = checkpoint_interval,
        num_classes = num_classes,
        epochs_2_3 = (req.epochs as f64 * 0.67) as u32,
        epochs_8_9 = (req.epochs as f64 * 0.89) as u32,
    )
}

pub fn generate_mmdet_train_script(config_path: &str) -> String {
    format!(
        r#"#!/usr/bin/env python3
"""
MMDetection Training Script - Generated by Annotix
"""
import sys
import json
import os

def main():
    from mmengine.config import Config
    from mmengine.runner import Runner
    from mmengine.hooks import Hook

    class AnnotixHook(Hook):
        def after_train_epoch(self, runner):
            epoch = runner.epoch + 1
            total = runner.max_epochs
            progress = (epoch / total) * 100.0

            metrics = {{}}
            if hasattr(runner, 'message_hub'):
                log_scalars = runner.message_hub.log_scalars
                for key in ["loss", "loss_cls", "loss_bbox"]:
                    full_key = f"train/{{key}}"
                    if full_key in log_scalars:
                        val = log_scalars[full_key]
                        if hasattr(val, 'current'):
                            val = val.current()
                        metrics["trainLoss"] = float(val) if key == "loss" else metrics.get("trainLoss")
                        if key == "loss_cls":
                            metrics["clsLoss"] = float(val)
                        if key == "loss_bbox":
                            metrics["boxLoss"] = float(val)

            event = {{
                "type": "epoch",
                "epoch": epoch,
                "totalEpochs": total,
                "progress": progress,
                "metrics": metrics,
            }}
            print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

        def after_val_epoch(self, runner, metrics=None):
            if metrics:
                result_metrics = {{}}
                result_metrics["mAP50"] = metrics.get("coco/bbox_mAP_50", None)
                result_metrics["mAP50_95"] = metrics.get("coco/bbox_mAP", None)
                event = {{
                    "type": "epoch",
                    "epoch": runner.epoch + 1,
                    "totalEpochs": runner.max_epochs,
                    "progress": ((runner.epoch + 1) / runner.max_epochs) * 100.0,
                    "metrics": result_metrics,
                }}
                print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    config_path = r"{config_path}"
    cfg = Config.fromfile(config_path)

    # Set work_dir
    cfg.work_dir = os.path.join(os.path.dirname(config_path), "train")
    os.makedirs(cfg.work_dir, exist_ok=True)

    # Build runner
    runner = Runner.from_cfg(cfg)
    runner.register_hook(AnnotixHook(), priority="LOW")
    runner.train()

    # Completed
    best_ckpt = os.path.join(cfg.work_dir, "best_coco_bbox_mAP_epoch_*.pth")
    import glob
    best_files = sorted(glob.glob(best_ckpt))
    best_model = best_files[-1] if best_files else None

    result = {{
        "type": "completed",
        "bestModelPath": best_model,
        "lastModelPath": None,
        "resultsDir": cfg.work_dir,
    }}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        config_path = config_path.replace('\\', "/"),
    )
}

// ─── Script Router ───────────────────────────────────────────────────────────

/// Returns Vec<(filename, content)> — MMDet generates 2 files, others 1
pub fn generate_train_script_for_backend(
    req: &TrainingRequest,
    dataset_path: &str,
    num_classes: usize,
) -> Vec<(String, String)> {
    match req.backend {
        TrainingBackend::Yolo => {
            // Shouldn't reach here normally (uses legacy path), but handle it
            let config = super::TrainingConfig {
                yolo_version: req.model_id.clone(),
                task: req.task.clone(),
                model_size: req.backend_params.get("modelSize")
                    .and_then(|v| v.as_str()).unwrap_or("n").to_string(),
                epochs: req.epochs,
                batch_size: req.batch_size,
                imgsz: req.image_size,
                device: req.device.clone(),
                optimizer: req.backend_params.get("optimizer")
                    .and_then(|v| v.as_str()).unwrap_or("auto").to_string(),
                lr0: req.lr,
                lrf: req.backend_params.get("lrf").and_then(|v| v.as_f64()).unwrap_or(0.01),
                patience: req.patience,
                val_split: req.val_split,
                workers: req.workers,
                augmentation: serde_json::from_value(
                    req.backend_params.get("augmentation").cloned().unwrap_or_default()
                ).unwrap_or_else(|_| super::AugmentationConfig {
                    mosaic: 1.0, mixup: 0.0, hsv_h: 0.015, hsv_s: 0.7, hsv_v: 0.4,
                    flipud: 0.0, fliplr: 0.5, degrees: 0.0, scale: 0.5, shear: 0.0,
                    perspective: 0.0, copy_paste: 0.0, erasing: 0.4, translate: 0.1,
                }),
                export_formats: req.export_formats.clone(),
                resume: req.resume,
                cos_lr: false,
                warmup_epochs: 3.0,
                warmup_momentum: 0.8,
                warmup_bias_lr: 0.1,
                momentum: 0.937,
                weight_decay: 0.0005,
                nbs: 64,
                box_weight: 7.5,
                cls: 0.5,
                dfl: 1.5,
                close_mosaic: 10,
                max_det: 300,
                multi_scale: 0.0,
                rect: false,
                cache: super::CacheOption::Bool(false),
                amp: req.amp,
                single_cls: false,
                pretrained: true,
                freeze: None,
                base_model_path: req.base_model_path.clone(),
            };
            vec![("train.py".to_string(), generate_train_script(&config, dataset_path))]
        }
        TrainingBackend::RtDetr => {
            vec![("train.py".to_string(), generate_rtdetr_script(req, dataset_path))]
        }
        TrainingBackend::RfDetr => {
            vec![("train.py".to_string(), generate_rfdetr_script(req, dataset_path))]
        }
        TrainingBackend::MmDetection => {
            let config_content = generate_mmdet_config(req, dataset_path, num_classes);
            let config_path = format!("{}/mmdet_config.py", dataset_path.replace('\\', "/"));
            let train_content = generate_mmdet_train_script(&config_path);
            vec![
                ("mmdet_config.py".to_string(), config_content),
                ("train.py".to_string(), train_content),
            ]
        }
        TrainingBackend::Smp => {
            vec![("train.py".to_string(), generate_smp_script(req, dataset_path, num_classes))]
        }
        TrainingBackend::HfSegmentation => {
            vec![("train.py".to_string(), generate_hf_seg_script(req, dataset_path, num_classes))]
        }
        TrainingBackend::MmSegmentation => {
            let config_content = generate_mmseg_config(req, dataset_path, num_classes);
            let config_path = format!("{}/mmseg_config.py", dataset_path.replace('\\', "/"));
            let train_content = generate_mmseg_train_script(&config_path);
            vec![
                ("mmseg_config.py".to_string(), config_content),
                ("train.py".to_string(), train_content),
            ]
        }
    }
}

/// Returns pip requirements for a backend
pub fn get_requirements_for_backend(backend: &TrainingBackend) -> Vec<&'static str> {
    match backend {
        TrainingBackend::Yolo | TrainingBackend::RtDetr => vec!["ultralytics"],
        TrainingBackend::RfDetr => vec!["rfdetr", "torch", "torchvision"],
        TrainingBackend::MmDetection => vec!["openmim", "mmengine", "mmcv", "mmdet", "torch", "torchvision"],
        TrainingBackend::Smp => vec!["segmentation-models-pytorch", "torch", "torchvision", "albumentations"],
        TrainingBackend::HfSegmentation => vec!["transformers", "datasets", "evaluate", "torch", "torchvision"],
        TrainingBackend::MmSegmentation => vec!["openmim", "mmengine", "mmcv", "mmsegmentation", "torch", "torchvision"],
    }
}

// ─── SMP Script ──────────────────────────────────────────────────────────────

pub fn generate_smp_script(req: &TrainingRequest, dataset_dir: &str, num_classes: usize) -> String {
    let bp = &req.backend_params;
    let model_id = &req.model_id; // e.g. "Unet-resnet34"
    let parts: Vec<&str> = model_id.splitn(2, '-').collect();
    let arch = parts.first().unwrap_or(&"Unet");
    let encoder = if parts.len() > 1 { parts[1] } else { "resnet34" };

    let loss_type = bp.get("loss_type").and_then(|v| v.as_str()).unwrap_or("dice+ce");
    let scheduler = bp.get("scheduler").and_then(|v| v.as_str()).unwrap_or("cosine");
    let encoder_depth = bp.get("encoder_depth").and_then(|v| v.as_u64()).unwrap_or(5);
    let freeze_encoder = bp.get("freeze_encoder").and_then(|v| v.as_bool()).unwrap_or(false);
    let device = format_device(&req.device);

    let dataset_dir_escaped = dataset_dir.replace('\\', "/");

    format!(
        r#"#!/usr/bin/env python3
"""
SMP Training Script - Generated by Annotix
Architecture: {arch} | Encoder: {encoder}
"""
import sys
import json
import os
import numpy as np
from pathlib import Path

def main():
    import torch
    import torch.nn as nn
    from torch.utils.data import Dataset, DataLoader
    import segmentation_models_pytorch as smp
    from PIL import Image
    import albumentations as A
    from albumentations.pytorch import ToTensorV2

    device = torch.device({device} if {device} != "" else ("cuda" if torch.cuda.is_available() else "cpu"))

    dataset_dir = r"{dataset_dir}"
    output_dir = os.path.join(dataset_dir, "train_output")
    os.makedirs(output_dir, exist_ok=True)

    num_classes = {num_classes} + 1  # +1 for background

    # Build model
    model = smp.create_model(
        arch="{arch}",
        encoder_name="{encoder}",
        encoder_weights="imagenet",
        in_channels=3,
        classes=num_classes,
        encoder_depth={encoder_depth},
    )
    if {freeze_encoder}:
        for param in model.encoder.parameters():
            param.requires_grad = False
    model = model.to(device)

    # Loss
    loss_type = "{loss_type}"
    if loss_type == "dice":
        criterion = smp.losses.DiceLoss(mode="multiclass")
    elif loss_type == "ce":
        criterion = nn.CrossEntropyLoss()
    elif loss_type == "focal":
        criterion = smp.losses.FocalLoss(mode="multiclass")
    elif loss_type == "jaccard":
        criterion = smp.losses.JaccardLoss(mode="multiclass")
    else:  # dice+ce
        dice_loss = smp.losses.DiceLoss(mode="multiclass")
        ce_loss = nn.CrossEntropyLoss()
        criterion = lambda pred, target: dice_loss(pred, target) + ce_loss(pred, target)

    # Dataset
    img_size = {imgsz}
    train_transform = A.Compose([
        A.Resize(img_size, img_size),
        A.HorizontalFlip(p=0.5),
        A.RandomBrightnessContrast(p=0.3),
        A.Normalize(),
        ToTensorV2(),
    ])
    val_transform = A.Compose([
        A.Resize(img_size, img_size),
        A.Normalize(),
        ToTensorV2(),
    ])

    class SegDataset(Dataset):
        def __init__(self, images_dir, masks_dir, transform=None):
            self.images = sorted(Path(images_dir).glob("*"))
            self.masks_dir = Path(masks_dir)
            self.transform = transform

        def __len__(self):
            return len(self.images)

        def __getitem__(self, idx):
            img_path = self.images[idx]
            mask_name = img_path.stem + ".png"
            mask_path = self.masks_dir / mask_name
            image = np.array(Image.open(img_path).convert("RGB"))
            mask = np.array(Image.open(mask_path)) if mask_path.exists() else np.zeros(image.shape[:2], dtype=np.uint8)
            if self.transform:
                augmented = self.transform(image=image, mask=mask)
                image, mask = augmented["image"], augmented["mask"]
            return image, mask.long()

    train_ds = SegDataset(os.path.join(dataset_dir, "images/train"), os.path.join(dataset_dir, "masks/train"), train_transform)
    val_ds = SegDataset(os.path.join(dataset_dir, "images/val"), os.path.join(dataset_dir, "masks/val"), val_transform)

    train_loader = DataLoader(train_ds, batch_size={batch}, shuffle=True, num_workers={workers}, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size={batch}, shuffle=False, num_workers={workers}, pin_memory=True)

    # Optimizer & scheduler
    optimizer = torch.optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr={lr}, weight_decay=1e-4)
    scheduler_type = "{scheduler}"
    if scheduler_type == "cosine":
        scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max={epochs})
    elif scheduler_type == "poly":
        scheduler = torch.optim.lr_scheduler.PolynomialLR(optimizer, total_iters={epochs}, power=0.9)
    else:
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=max(1, {epochs}//3), gamma=0.1)

    scaler = torch.amp.GradScaler("cuda") if {amp} and device.type == "cuda" else None

    best_miou = 0.0
    patience_counter = 0

    for epoch in range(1, {epochs} + 1):
        # Train
        model.train()
        train_loss = 0.0
        for images, masks in train_loader:
            images, masks = images.to(device), masks.to(device)
            optimizer.zero_grad()
            if scaler:
                with torch.amp.autocast("cuda"):
                    outputs = model(images)
                    loss = criterion(outputs, masks)
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                outputs = model(images)
                loss = criterion(outputs, masks)
                loss.backward()
                optimizer.step()
            train_loss += loss.item()
        train_loss /= max(len(train_loader), 1)

        # Validate
        model.eval()
        val_loss = 0.0
        intersection = torch.zeros(num_classes, device=device)
        union = torch.zeros(num_classes, device=device)
        correct = torch.zeros(num_classes, device=device)
        total_pixels = torch.zeros(num_classes, device=device)

        with torch.no_grad():
            for images, masks in val_loader:
                images, masks = images.to(device), masks.to(device)
                outputs = model(images)
                loss = criterion(outputs, masks)
                val_loss += loss.item()
                preds = outputs.argmax(dim=1)
                for c in range(num_classes):
                    pred_c = (preds == c)
                    mask_c = (masks == c)
                    intersection[c] += (pred_c & mask_c).sum()
                    union[c] += (pred_c | mask_c).sum()
                    correct[c] += (pred_c & mask_c).sum()
                    total_pixels[c] += mask_c.sum()

        val_loss /= max(len(val_loader), 1)
        iou_per_class = intersection / (union + 1e-6)
        acc_per_class = correct / (total_pixels + 1e-6)
        valid_classes = total_pixels > 0
        mean_iou = iou_per_class[valid_classes].mean().item() if valid_classes.any() else 0.0
        mean_acc = acc_per_class[valid_classes].mean().item() if valid_classes.any() else 0.0

        scheduler.step()
        current_lr = optimizer.param_groups[0]["lr"]

        # Emit metrics
        event = {{
            "type": "epoch",
            "epoch": epoch,
            "totalEpochs": {epochs},
            "progress": (epoch / {epochs}) * 100.0,
            "metrics": {{
                "trainLoss": train_loss,
                "valLoss": val_loss,
                "meanIoU": mean_iou,
                "meanAccuracy": mean_acc,
                "lr": current_lr,
            }},
        }}
        print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

        # Save best
        if mean_iou > best_miou:
            best_miou = mean_iou
            torch.save(model.state_dict(), os.path.join(output_dir, "best.pth"))
            patience_counter = 0
        else:
            patience_counter += 1
            if {patience} > 0 and patience_counter >= {patience}:
                print(f"Early stopping at epoch {{epoch}}", flush=True)
                break

    # Save last
    torch.save(model.state_dict(), os.path.join(output_dir, "last.pth"))

    # Export ONNX
    try:
        model.eval()
        dummy = torch.randn(1, 3, img_size, img_size).to(device)
        onnx_path = os.path.join(output_dir, "model.onnx")
        torch.onnx.export(model, dummy, onnx_path, opset_version=17, input_names=["input"], output_names=["output"])
    except Exception as e:
        print(f"ONNX export failed: {{e}}", file=sys.stderr)

    result = {{
        "type": "completed",
        "bestModelPath": os.path.join(output_dir, "best.pth"),
        "lastModelPath": os.path.join(output_dir, "last.pth"),
        "resultsDir": output_dir,
    }}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        arch = arch,
        encoder = encoder,
        dataset_dir = dataset_dir_escaped,
        device = device,
        num_classes = num_classes,
        encoder_depth = encoder_depth,
        freeze_encoder = py_bool(freeze_encoder),
        loss_type = loss_type,
        imgsz = req.image_size,
        batch = req.batch_size,
        workers = req.workers,
        lr = req.lr,
        scheduler = scheduler,
        epochs = req.epochs,
        amp = py_bool(req.amp),
        patience = req.patience,
    )
}

// ─── HuggingFace Segmentation Script ─────────────────────────────────────────

pub fn generate_hf_seg_script(req: &TrainingRequest, dataset_dir: &str, num_classes: usize) -> String {
    let bp = &req.backend_params;
    let model_checkpoint = &req.model_id; // e.g. "nvidia/mit-b0"
    let do_reduce_labels = bp.get("do_reduce_labels").and_then(|v| v.as_bool()).unwrap_or(false);
    let warmup_ratio = bp.get("warmup_ratio").and_then(|v| v.as_f64()).unwrap_or(0.05);
    let weight_decay = bp.get("weight_decay").and_then(|v| v.as_f64()).unwrap_or(0.01);
    let lr_scheduler_type = bp.get("lr_scheduler_type").and_then(|v| v.as_str()).unwrap_or("cosine");

    let dataset_dir_escaped = dataset_dir.replace('\\', "/");

    format!(
        r#"#!/usr/bin/env python3
"""
HuggingFace Semantic Segmentation Training Script - Generated by Annotix
Model: {model_checkpoint}
"""
import sys
import json
import os
import numpy as np
from pathlib import Path

def main():
    import torch
    from torch.utils.data import Dataset, DataLoader
    from transformers import (
        SegformerForSemanticSegmentation,
        SegformerImageProcessor,
        TrainingArguments,
        Trainer,
    )
    from PIL import Image

    dataset_dir = r"{dataset_dir}"
    output_dir = os.path.join(dataset_dir, "train_output")
    os.makedirs(output_dir, exist_ok=True)

    num_classes = {num_classes} + 1  # +1 for background
    do_reduce_labels = {do_reduce_labels}

    # Load processor
    processor = SegformerImageProcessor.from_pretrained("{model_checkpoint}", do_reduce_labels=do_reduce_labels)

    class SegDataset(Dataset):
        def __init__(self, images_dir, masks_dir, processor):
            self.images = sorted(Path(images_dir).glob("*"))
            self.masks_dir = Path(masks_dir)
            self.processor = processor

        def __len__(self):
            return len(self.images)

        def __getitem__(self, idx):
            img_path = self.images[idx]
            mask_name = img_path.stem + ".png"
            mask_path = self.masks_dir / mask_name
            image = Image.open(img_path).convert("RGB")
            mask = Image.open(mask_path) if mask_path.exists() else Image.new("L", image.size, 0)
            encoded = self.processor(images=image, segmentation_maps=mask, return_tensors="pt")
            for k, v in encoded.items():
                encoded[k] = v.squeeze(0)
            return encoded

    train_ds = SegDataset(
        os.path.join(dataset_dir, "images/train"),
        os.path.join(dataset_dir, "masks/train"),
        processor,
    )
    val_ds = SegDataset(
        os.path.join(dataset_dir, "images/val"),
        os.path.join(dataset_dir, "masks/val"),
        processor,
    )

    # Model
    id2label = {{i: f"class_{{i}}" for i in range(num_classes)}}
    label2id = {{v: k for k, v in id2label.items()}}

    # Read class names from classes.txt if available
    classes_file = os.path.join(dataset_dir, "classes.txt")
    if os.path.exists(classes_file):
        with open(classes_file) as f:
            for line in f:
                parts = line.strip().split(": ", 1)
                if len(parts) == 2:
                    idx, name = int(parts[0]), parts[1]
                    if idx < num_classes:
                        id2label[idx] = name
                        label2id[name] = idx

    model = SegformerForSemanticSegmentation.from_pretrained(
        "{model_checkpoint}",
        num_labels=num_classes,
        id2label=id2label,
        label2id=label2id,
        ignore_mismatched_sizes=True,
    )

    # Training args
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs={epochs},
        per_device_train_batch_size={batch},
        per_device_eval_batch_size={batch},
        learning_rate={lr},
        lr_scheduler_type="{lr_scheduler_type}",
        warmup_ratio={warmup_ratio},
        weight_decay={weight_decay},
        eval_strategy="epoch",
        save_strategy="epoch",
        save_total_limit=2,
        load_best_model_at_end=True,
        metric_for_best_model="eval_mean_iou",
        greater_is_better=True,
        fp16={amp} and torch.cuda.is_available(),
        dataloader_num_workers={workers},
        logging_steps=10,
        remove_unused_columns=False,
    )

    # Metrics
    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        # logits shape: (batch, num_classes, H, W)
        if isinstance(logits, tuple):
            logits = logits[0]
        logits = torch.tensor(logits)
        labels = torch.tensor(labels)
        # Upsample logits to label size
        if logits.shape[-2:] != labels.shape[-2:]:
            logits = torch.nn.functional.interpolate(
                logits.float(), size=labels.shape[-2:], mode="bilinear", align_corners=False
            )
        preds = logits.argmax(dim=1)
        # Compute mean IoU
        ious = []
        accs = []
        for c in range(num_classes):
            pred_c = (preds == c)
            label_c = (labels == c)
            inter = (pred_c & label_c).sum().item()
            union = (pred_c | label_c).sum().item()
            total = label_c.sum().item()
            if total > 0:
                ious.append(inter / (union + 1e-6))
                accs.append(inter / (total + 1e-6))
        mean_iou = np.mean(ious) if ious else 0.0
        mean_acc = np.mean(accs) if accs else 0.0
        return {{"mean_iou": mean_iou, "mean_accuracy": mean_acc}}

    # Custom callback for Annotix events
    from transformers import TrainerCallback

    class AnnotixCallback(TrainerCallback):
        def on_epoch_end(self, args, state, control, **kwargs):
            epoch = int(state.epoch)
            total = {epochs}
            metrics = {{"lr": state.log_history[-1].get("learning_rate", None)}} if state.log_history else {{}}
            # Get train loss from recent logs
            for entry in reversed(state.log_history):
                if "loss" in entry:
                    metrics["trainLoss"] = entry["loss"]
                    break
            event = {{
                "type": "epoch",
                "epoch": epoch,
                "totalEpochs": total,
                "progress": (epoch / total) * 100.0,
                "metrics": metrics,
            }}
            print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

        def on_evaluate(self, args, state, control, metrics=None, **kwargs):
            if metrics:
                epoch = int(state.epoch)
                total = {epochs}
                event = {{
                    "type": "epoch",
                    "epoch": epoch,
                    "totalEpochs": total,
                    "progress": (epoch / total) * 100.0,
                    "metrics": {{
                        "valLoss": metrics.get("eval_loss", None),
                        "meanIoU": metrics.get("eval_mean_iou", None),
                        "meanAccuracy": metrics.get("eval_mean_accuracy", None),
                    }},
                }}
                print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        compute_metrics=compute_metrics,
        callbacks=[AnnotixCallback()],
    )

    trainer.train()

    # Save best
    trainer.save_model(os.path.join(output_dir, "best"))

    # Export ONNX
    try:
        onnx_path = os.path.join(output_dir, "model.onnx")
        dummy = torch.randn(1, 3, {imgsz}, {imgsz})
        torch.onnx.export(model.cpu(), dummy, onnx_path, opset_version=17, input_names=["input"], output_names=["output"])
    except Exception as e:
        print(f"ONNX export failed: {{e}}", file=sys.stderr)

    result = {{
        "type": "completed",
        "bestModelPath": os.path.join(output_dir, "best"),
        "lastModelPath": None,
        "resultsDir": output_dir,
    }}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        model_checkpoint = model_checkpoint,
        dataset_dir = dataset_dir_escaped,
        num_classes = num_classes,
        do_reduce_labels = py_bool(do_reduce_labels),
        epochs = req.epochs,
        batch = req.batch_size,
        lr = req.lr,
        lr_scheduler_type = lr_scheduler_type,
        warmup_ratio = warmup_ratio,
        weight_decay = weight_decay,
        amp = py_bool(req.amp),
        workers = req.workers,
        imgsz = req.image_size,
    )
}

// ─── MMSegmentation Config + Script ──────────────────────────────────────────

pub fn generate_mmseg_config(req: &TrainingRequest, dataset_dir: &str, num_classes: usize) -> String {
    let bp = &req.backend_params;
    let model_id = &req.model_id;
    let optimizer_type = bp.get("optimizer_type").and_then(|v| v.as_str()).unwrap_or("AdamW");
    let weight_decay = bp.get("weight_decay").and_then(|v| v.as_f64()).unwrap_or(0.01);
    let warmup_iters = bp.get("warmup_iters").and_then(|v| v.as_u64()).unwrap_or(500);
    let checkpoint_interval = bp.get("checkpoint_interval").and_then(|v| v.as_u64()).unwrap_or(1);
    let crop_size = bp.get("crop_size").and_then(|v| v.as_u64()).unwrap_or(512);
    let lr_schedule = bp.get("lr_schedule").and_then(|v| v.as_str()).unwrap_or("poly");

    let dataset_dir_escaped = dataset_dir.replace('\\', "/");
    let num_classes_with_bg = num_classes + 1;

    let lr_schedule_config = match lr_schedule {
        "cosine" => format!(
            "param_scheduler = [\n    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end={warmup_iters}),\n    dict(type='CosineAnnealingLR', by_epoch=True, T_max={epochs}),\n]",
            warmup_iters = warmup_iters, epochs = req.epochs
        ),
        "step" => format!(
            "param_scheduler = [\n    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end={warmup_iters}),\n    dict(type='MultiStepLR', by_epoch=True, milestones=[{m1}, {m2}], gamma=0.1),\n]",
            warmup_iters = warmup_iters,
            m1 = (req.epochs as f64 * 0.67) as u32,
            m2 = (req.epochs as f64 * 0.89) as u32,
        ),
        _ => format!(
            "param_scheduler = [\n    dict(type='LinearLR', start_factor=0.001, by_epoch=False, begin=0, end={warmup_iters}),\n    dict(type='PolyLR', by_epoch=True, eta_min=1e-6, power=0.9),\n]",
            warmup_iters = warmup_iters,
        ),
    };

    format!(
        r#"# MMSegmentation Config - Generated by Annotix
_base_ = []

model_name = "{model_id}"

# Dataset
dataset_type = "BaseSegDataset"
data_root = r"{dataset_dir}"
crop_size = ({crop_size}, {crop_size})

train_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(type="LoadAnnotations"),
    dict(type="RandomCrop", crop_size=crop_size),
    dict(type="RandomFlip", prob=0.5),
    dict(type="PackSegInputs"),
]

val_pipeline = [
    dict(type="LoadImageFromFile"),
    dict(type="LoadAnnotations"),
    dict(type="Resize", scale=crop_size),
    dict(type="PackSegInputs"),
]

train_dataloader = dict(
    batch_size={batch},
    num_workers={workers},
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path="images/train", seg_map_path="masks/train"),
        pipeline=train_pipeline,
    ),
)

val_dataloader = dict(
    batch_size=1,
    num_workers={workers},
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_prefix=dict(img_path="images/val", seg_map_path="masks/val"),
        pipeline=val_pipeline,
    ),
)

val_evaluator = dict(type="IoUMetric", iou_metrics=["mIoU"])

# Optimizer
optim_wrapper = dict(
    type="OptimWrapper",
    optimizer=dict(type="{optimizer_type}", lr={lr}, weight_decay={weight_decay}),
)

# Schedule
train_cfg = dict(type="EpochBasedTrainLoop", max_epochs={epochs}, val_interval=1)
val_cfg = dict(type="ValLoop")
{lr_schedule_config}

# Runtime
default_hooks = dict(
    checkpoint=dict(type="CheckpointHook", interval={checkpoint_interval}),
)

num_classes = {num_classes_with_bg}
"#,
        model_id = model_id,
        dataset_dir = dataset_dir_escaped,
        crop_size = crop_size,
        batch = req.batch_size,
        workers = req.workers,
        optimizer_type = optimizer_type,
        lr = req.lr,
        weight_decay = weight_decay,
        epochs = req.epochs,
        lr_schedule_config = lr_schedule_config,
        checkpoint_interval = checkpoint_interval,
        num_classes_with_bg = num_classes_with_bg,
    )
}

pub fn generate_mmseg_train_script(config_path: &str) -> String {
    format!(
        r#"#!/usr/bin/env python3
"""
MMSegmentation Training Script - Generated by Annotix
"""
import sys
import json
import os

def main():
    from mmengine.config import Config
    from mmengine.runner import Runner
    from mmengine.hooks import Hook

    class AnnotixHook(Hook):
        def after_train_epoch(self, runner):
            epoch = runner.epoch + 1
            total = runner.max_epochs
            progress = (epoch / total) * 100.0

            metrics = {{}}
            if hasattr(runner, 'message_hub'):
                log_scalars = runner.message_hub.log_scalars
                for key in ["loss", "decode.loss_ce", "decode.loss_seg"]:
                    full_key = f"train/{{key}}"
                    if full_key in log_scalars:
                        val = log_scalars[full_key]
                        if hasattr(val, 'current'):
                            val = val.current()
                        if key == "loss":
                            metrics["trainLoss"] = float(val)
                        elif "ce" in key:
                            metrics["segLoss"] = float(val)

            event = {{
                "type": "epoch",
                "epoch": epoch,
                "totalEpochs": total,
                "progress": progress,
                "metrics": metrics,
            }}
            print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

        def after_val_epoch(self, runner, metrics=None):
            if metrics:
                result_metrics = {{}}
                result_metrics["meanIoU"] = metrics.get("aAcc", None)
                result_metrics["meanAccuracy"] = metrics.get("mAcc", None)
                # mIoU from IoUMetric
                for key in metrics:
                    if "mIoU" in key:
                        result_metrics["meanIoU"] = metrics[key]
                event = {{
                    "type": "epoch",
                    "epoch": runner.epoch + 1,
                    "totalEpochs": runner.max_epochs,
                    "progress": ((runner.epoch + 1) / runner.max_epochs) * 100.0,
                    "metrics": result_metrics,
                }}
                print("ANNOTIX_EVENT:" + json.dumps(event), flush=True)

    config_path = r"{config_path}"
    cfg = Config.fromfile(config_path)

    cfg.work_dir = os.path.join(os.path.dirname(config_path), "train")
    os.makedirs(cfg.work_dir, exist_ok=True)

    runner = Runner.from_cfg(cfg)
    runner.register_hook(AnnotixHook(), priority="LOW")
    runner.train()

    # Find best checkpoint
    best_ckpt = os.path.join(cfg.work_dir, "best_mIoU_epoch_*.pth")
    import glob
    best_files = sorted(glob.glob(best_ckpt))
    best_model = best_files[-1] if best_files else None

    result = {{
        "type": "completed",
        "bestModelPath": best_model,
        "lastModelPath": None,
        "resultsDir": cfg.work_dir,
    }}
    print("ANNOTIX_EVENT:" + json.dumps(result), flush=True)

if __name__ == "__main__":
    main()
"#,
        config_path = config_path.replace('\\', "/"),
    )
}

fn generate_export_section(formats: &[String]) -> String {
    if formats.is_empty() {
        return "# No export formats requested".to_string();
    }

    let mut lines = vec![
        "    # Export model to requested formats".to_string(),
        "    exported = []".to_string(),
        format!("    best = YOLO(best_model) if os.path.exists(best_model) else model"),
    ];

    for fmt in formats {
        lines.push(format!(
            "    try:\n        export_path = best.export(format=\"{fmt}\")\n        exported.append({{\"format\": \"{fmt}\", \"path\": str(export_path)}})\n    except Exception as e:\n        print(f\"Warning: export to {fmt} failed: {{e}}\", file=sys.stderr)",
            fmt = fmt,
        ));
    }

    lines.push("    result[\"exportedModels\"] = exported".to_string());
    lines.join("\n")
}
