use std::io::Write;
use std::path::Path;
use zip::write::SimpleFileOptions;
use zip::ZipWriter;

use crate::store::project_file::{ProjectFile, ImageEntry};
use crate::utils::converters::normalize_coordinates;
use super::{parse_bbox, parse_obb, add_image_to_zip};

/// COCO-17 skeleton keypoint names
const COCO17_POINTS: &[&str] = &[
    "nose", "left_eye", "right_eye", "left_ear", "right_ear",
    "left_shoulder", "right_shoulder", "left_elbow", "right_elbow",
    "left_wrist", "right_wrist", "left_hip", "right_hip",
    "left_knee", "right_knee", "left_ankle", "right_ankle",
];

const COCO17_CONNECTIONS: &[[usize; 2]] = &[
    [0, 1], [0, 2], [1, 3], [2, 4], [0, 5], [0, 6],
    [5, 6], [5, 7], [7, 9], [6, 8], [8, 10],
    [5, 11], [6, 12], [11, 12], [11, 13], [13, 15], [12, 14], [14, 16],
];

pub fn export<F: Fn(f64)>(
    project: &ProjectFile,
    images: &[ImageEntry],
    images_dir: &Path,
    file: std::fs::File,
    _include_segmentation: bool,
    emit_progress: F,
) -> Result<(), String> {
    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);

    // classes.txt
    let classes_content: String = project.classes.iter().map(|c| c.name.as_str()).collect::<Vec<_>>().join("\n");
    zip.start_file("classes.txt", options).map_err(|e| e.to_string())?;
    zip.write_all(classes_content.as_bytes()).map_err(|e| e.to_string())?;

    // data.yaml
    let yaml_content = generate_data_yaml(project);
    zip.start_file("data.yaml", options).map_err(|e| e.to_string())?;
    zip.write_all(yaml_content.as_bytes()).map_err(|e| e.to_string())?;

    let total = images.len() as f64;

    for (i, image) in images.iter().enumerate() {
        // Add image
        add_image_to_zip(&mut zip, "images", image, images_dir)?;

        // Generate label
        let label = generate_label(image, project);
        let label_name = replace_ext(&image.name, "txt");
        zip.start_file(format!("labels/{}", label_name), options).map_err(|e| e.to_string())?;
        zip.write_all(label.as_bytes()).map_err(|e| e.to_string())?;

        emit_progress(((i + 1) as f64 / total) * 100.0);
    }

    zip.finish().map_err(|e| e.to_string())?;
    Ok(())
}

fn generate_data_yaml(project: &ProjectFile) -> String {
    let mut lines = vec![
        "# YOLO Dataset Configuration".to_string(),
        "# Generated by Annotix".to_string(),
        String::new(),
        "path: .".to_string(),
        "train: images".to_string(),
        "val: images".to_string(),
        String::new(),
        format!("nc: {}", project.classes.len()),
        "names:".to_string(),
    ];

    for cls in &project.classes {
        lines.push(format!("  {}: {}", cls.id, cls.name));
    }

    if project.project_type == "keypoints" {
        lines.push(String::new());
        lines.push("# Keypoints configuration".to_string());
        lines.push(format!("kpt_shape: [{}, 3]  # number of keypoints, number of dims (x, y, visibility)", COCO17_POINTS.len()));
        lines.push(String::new());
        lines.push("# Keypoint names".to_string());
        lines.push("keypoint_names:".to_string());
        for (idx, name) in COCO17_POINTS.iter().enumerate() {
            lines.push(format!("  {}: {}", idx, name));
        }
        lines.push(String::new());
        lines.push("# Skeleton connections (for visualization)".to_string());
        lines.push("skeleton:".to_string());
        for conn in COCO17_CONNECTIONS {
            lines.push(format!("  - [{}, {}]", conn[0], conn[1]));
        }
    }

    lines.join("\n")
}

fn generate_label(image: &ImageEntry, _project: &ProjectFile) -> String {
    let mut lines = Vec::new();

    for ann in &image.annotations {
        match ann.annotation_type.as_str() {
            "bbox" => {
                if let Some(bbox) = parse_bbox(&ann.data) {
                    let (nx, ny, nw, nh) = normalize_coordinates(
                        bbox.x, bbox.y, bbox.width, bbox.height,
                        image.width as f64, image.height as f64,
                    );
                    let x_center = nx + nw / 2.0;
                    let y_center = ny + nh / 2.0;
                    lines.push(format!(
                        "{} {:.6} {:.6} {:.6} {:.6}",
                        ann.class_id, x_center, y_center, nw, nh
                    ));
                }
            }
            "obb" => {
                if let Some(obb) = parse_obb(&ann.data) {
                    // Convert OBB to axis-aligned for YOLO
                    let (min_x, min_y, max_x, max_y) = crate::utils::converters::obb_to_aabbox(
                        obb.x, obb.y, obb.width, obb.height, obb.rotation,
                    );
                    let w = max_x - min_x;
                    let h = max_y - min_y;
                    let (nx, ny, nw, nh) = normalize_coordinates(
                        min_x, min_y, w, h,
                        image.width as f64, image.height as f64,
                    );
                    let x_center = nx + nw / 2.0;
                    let y_center = ny + nh / 2.0;
                    lines.push(format!(
                        "{} {:.6} {:.6} {:.6} {:.6}",
                        ann.class_id, x_center, y_center, nw, nh
                    ));
                }
            }
            _ => {}
        }
    }

    lines.join("\n")
}

fn replace_ext(filename: &str, new_ext: &str) -> String {
    match filename.rfind('.') {
        Some(pos) => format!("{}.{}", &filename[..pos], new_ext),
        None => format!("{}.{}", filename, new_ext),
    }
}
